/**
 * Pre-computed deterministic prediction results.
 * Generated by scripts/regen_deterministic.py
 *
 * This is the model's single best answer — argmax of predicted probabilities
 * for every match. Unlike Monte Carlo simulation, this always produces the
 * same result.
 */

export const DETERMINISTIC_DATA = {
  "champion": "France",
  "groups": [
    {
      "group": "A",
      "matches": [
        {
          "home_team": "Mexico",
          "away_team": "South Africa",
          "home_goals": 2,
          "away_goals": 0,
          "home_pts": 3,
          "away_pts": 0,
          "prob_home": 0.7181,
          "prob_draw": 0.2099,
          "prob_away": 0.0721
        },
        {
          "home_team": "South Korea",
          "away_team": "Czech Republic",
          "home_goals": 2,
          "away_goals": 1,
          "home_pts": 3,
          "away_pts": 0,
          "prob_home": 0.5674,
          "prob_draw": 0.2523,
          "prob_away": 0.1802
        },
        {
          "home_team": "Czech Republic",
          "away_team": "South Africa",
          "home_goals": 2,
          "away_goals": 1,
          "home_pts": 3,
          "away_pts": 0,
          "prob_home": 0.5266,
          "prob_draw": 0.2778,
          "prob_away": 0.1957
        },
        {
          "home_team": "Mexico",
          "away_team": "South Korea",
          "home_goals": 2,
          "away_goals": 1,
          "home_pts": 3,
          "away_pts": 0,
          "prob_home": 0.5534,
          "prob_draw": 0.296,
          "prob_away": 0.1506
        },
        {
          "home_team": "Czech Republic",
          "away_team": "Mexico",
          "home_goals": 1,
          "away_goals": 2,
          "home_pts": 0,
          "away_pts": 3,
          "prob_home": 0.2984,
          "prob_draw": 0.2702,
          "prob_away": 0.4314
        },
        {
          "home_team": "South Africa",
          "away_team": "South Korea",
          "home_goals": 1,
          "away_goals": 2,
          "home_pts": 0,
          "away_pts": 3,
          "prob_home": 0.268,
          "prob_draw": 0.3177,
          "prob_away": 0.4144
        }
      ],
      "table": [
        {
          "team": "Mexico",
          "pts": 9,
          "gd": 4,
          "gf": 6,
          "ga": 2,
          "mp": 3,
          "w": 3,
          "d": 0,
          "l": 0
        },
        {
          "team": "South Korea",
          "pts": 6,
          "gd": 1,
          "gf": 5,
          "ga": 4,
          "mp": 3,
          "w": 2,
          "d": 0,
          "l": 1
        },
        {
          "team": "Czech Republic",
          "pts": 3,
          "gd": -1,
          "gf": 4,
          "ga": 5,
          "mp": 3,
          "w": 1,
          "d": 0,
          "l": 2
        },
        {
          "team": "South Africa",
          "pts": 0,
          "gd": -4,
          "gf": 2,
          "ga": 6,
          "mp": 3,
          "w": 0,
          "d": 0,
          "l": 3
        }
      ]
    },
    {
      "group": "B",
      "matches": [
        {
          "home_team": "Canada",
          "away_team": "Bosnia and Herzegovina",
          "home_goals": 2,
          "away_goals": 1,
          "home_pts": 3,
          "away_pts": 0,
          "prob_home": 0.7846,
          "prob_draw": 0.149,
          "prob_away": 0.0663
        },
        {
          "home_team": "Qatar",
          "away_team": "Switzerland",
          "home_goals": 1,
          "away_goals": 2,
          "home_pts": 0,
          "away_pts": 3,
          "prob_home": 0.2196,
          "prob_draw": 0.2594,
          "prob_away": 0.521
        },
        {
          "home_team": "Switzerland",
          "away_team": "Bosnia and Herzegovina",
          "home_goals": 2,
          "away_goals": 1,
          "home_pts": 3,
          "away_pts": 0,
          "prob_home": 0.767,
          "prob_draw": 0.1616,
          "prob_away": 0.0714
        },
        {
          "home_team": "Canada",
          "away_team": "Qatar",
          "home_goals": 2,
          "away_goals": 0,
          "home_pts": 3,
          "away_pts": 0,
          "prob_home": 0.7197,
          "prob_draw": 0.2036,
          "prob_away": 0.0767
        },
        {
          "home_team": "Switzerland",
          "away_team": "Canada",
          "home_goals": 2,
          "away_goals": 1,
          "home_pts": 3,
          "away_pts": 0,
          "prob_home": 0.5349,
          "prob_draw": 0.2552,
          "prob_away": 0.2099
        },
        {
          "home_team": "Bosnia and Herzegovina",
          "away_team": "Qatar",
          "home_goals": 2,
          "away_goals": 1,
          "home_pts": 3,
          "away_pts": 0,
          "prob_home": 0.3675,
          "prob_draw": 0.2815,
          "prob_away": 0.3509
        }
      ],
      "table": [
        {
          "team": "Switzerland",
          "pts": 9,
          "gd": 3,
          "gf": 6,
          "ga": 3,
          "mp": 3,
          "w": 3,
          "d": 0,
          "l": 0
        },
        {
          "team": "Canada",
          "pts": 6,
          "gd": 2,
          "gf": 5,
          "ga": 3,
          "mp": 3,
          "w": 2,
          "d": 0,
          "l": 1
        },
        {
          "team": "Bosnia and Herzegovina",
          "pts": 3,
          "gd": -1,
          "gf": 4,
          "ga": 5,
          "mp": 3,
          "w": 1,
          "d": 0,
          "l": 2
        },
        {
          "team": "Qatar",
          "pts": 0,
          "gd": -4,
          "gf": 2,
          "ga": 6,
          "mp": 3,
          "w": 0,
          "d": 0,
          "l": 3
        }
      ]
    },
    {
      "group": "C",
      "matches": [
        {
          "home_team": "Brazil",
          "away_team": "Morocco",
          "home_goals": 2,
          "away_goals": 1,
          "home_pts": 3,
          "away_pts": 0,
          "prob_home": 0.4763,
          "prob_draw": 0.304,
          "prob_away": 0.2197
        },
        {
          "home_team": "Haiti",
          "away_team": "Scotland",
          "home_goals": 1,
          "away_goals": 2,
          "home_pts": 0,
          "away_pts": 3,
          "prob_home": 0.3598,
          "prob_draw": 0.2638,
          "prob_away": 0.3763
        },
        {
          "home_team": "Scotland",
          "away_team": "Morocco",
          "home_goals": 1,
          "away_goals": 2,
          "home_pts": 0,
          "away_pts": 3,
          "prob_home": 0.1747,
          "prob_draw": 0.2635,
          "prob_away": 0.5618
        },
        {
          "home_team": "Brazil",
          "away_team": "Haiti",
          "home_goals": 3,
          "away_goals": 0,
          "home_pts": 3,
          "away_pts": 0,
          "prob_home": 0.8662,
          "prob_draw": 0.1009,
          "prob_away": 0.0329
        },
        {
          "home_team": "Scotland",
          "away_team": "Brazil",
          "home_goals": 1,
          "away_goals": 2,
          "home_pts": 0,
          "away_pts": 3,
          "prob_home": 0.1977,
          "prob_draw": 0.2516,
          "prob_away": 0.5507
        },
        {
          "home_team": "Morocco",
          "away_team": "Haiti",
          "home_goals": 2,
          "away_goals": 0,
          "home_pts": 3,
          "away_pts": 0,
          "prob_home": 0.8226,
          "prob_draw": 0.1345,
          "prob_away": 0.0428
        }
      ],
      "table": [
        {
          "team": "Brazil",
          "pts": 9,
          "gd": 5,
          "gf": 7,
          "ga": 2,
          "mp": 3,
          "w": 3,
          "d": 0,
          "l": 0
        },
        {
          "team": "Morocco",
          "pts": 6,
          "gd": 2,
          "gf": 5,
          "ga": 3,
          "mp": 3,
          "w": 2,
          "d": 0,
          "l": 1
        },
        {
          "team": "Scotland",
          "pts": 3,
          "gd": -1,
          "gf": 4,
          "ga": 5,
          "mp": 3,
          "w": 1,
          "d": 0,
          "l": 2
        },
        {
          "team": "Haiti",
          "pts": 0,
          "gd": -6,
          "gf": 1,
          "ga": 7,
          "mp": 3,
          "w": 0,
          "d": 0,
          "l": 3
        }
      ]
    },
    {
      "group": "D",
      "matches": [
        {
          "home_team": "United States",
          "away_team": "Paraguay",
          "home_goals": 2,
          "away_goals": 1,
          "home_pts": 3,
          "away_pts": 0,
          "prob_home": 0.5132,
          "prob_draw": 0.2873,
          "prob_away": 0.1995
        },
        {
          "home_team": "Australia",
          "away_team": "Turkey",
          "home_goals": 2,
          "away_goals": 1,
          "home_pts": 3,
          "away_pts": 0,
          "prob_home": 0.5033,
          "prob_draw": 0.2533,
          "prob_away": 0.2434
        },
        {
          "home_team": "United States",
          "away_team": "Australia",
          "home_goals": 2,
          "away_goals": 1,
          "home_pts": 3,
          "away_pts": 0,
          "prob_home": 0.3987,
          "prob_draw": 0.3056,
          "prob_away": 0.2958
        },
        {
          "home_team": "Turkey",
          "away_team": "Paraguay",
          "home_goals": 2,
          "away_goals": 1,
          "home_pts": 3,
          "away_pts": 0,
          "prob_home": 0.5322,
          "prob_draw": 0.2615,
          "prob_away": 0.2063
        },
        {
          "home_team": "Turkey",
          "away_team": "United States",
          "home_goals": 2,
          "away_goals": 1,
          "home_pts": 3,
          "away_pts": 0,
          "prob_home": 0.4731,
          "prob_draw": 0.2523,
          "prob_away": 0.2746
        },
        {
          "home_team": "Paraguay",
          "away_team": "Australia",
          "home_goals": 2,
          "away_goals": 1,
          "home_pts": 3,
          "away_pts": 0,
          "prob_home": 0.3957,
          "prob_draw": 0.3044,
          "prob_away": 0.3
        }
      ],
      "table": [
        {
          "team": "United States",
          "pts": 6,
          "gd": 1,
          "gf": 5,
          "ga": 4,
          "mp": 3,
          "w": 2,
          "d": 0,
          "l": 1
        },
        {
          "team": "Turkey",
          "pts": 6,
          "gd": 1,
          "gf": 5,
          "ga": 4,
          "mp": 3,
          "w": 2,
          "d": 0,
          "l": 1
        },
        {
          "team": "Paraguay",
          "pts": 3,
          "gd": -1,
          "gf": 4,
          "ga": 5,
          "mp": 3,
          "w": 1,
          "d": 0,
          "l": 2
        },
        {
          "team": "Australia",
          "pts": 3,
          "gd": -1,
          "gf": 4,
          "ga": 5,
          "mp": 3,
          "w": 1,
          "d": 0,
          "l": 2
        }
      ]
    },
    {
      "group": "E",
      "matches": [
        {
          "home_team": "Germany",
          "away_team": "Curaçao",
          "home_goals": 3,
          "away_goals": 1,
          "home_pts": 3,
          "away_pts": 0,
          "prob_home": 0.7794,
          "prob_draw": 0.1438,
          "prob_away": 0.0768
        },
        {
          "home_team": "Ivory Coast",
          "away_team": "Ecuador",
          "home_goals": 1,
          "away_goals": 2,
          "home_pts": 0,
          "away_pts": 3,
          "prob_home": 0.2815,
          "prob_draw": 0.329,
          "prob_away": 0.3895
        },
        {
          "home_team": "Germany",
          "away_team": "Ivory Coast",
          "home_goals": 2,
          "away_goals": 1,
          "home_pts": 3,
          "away_pts": 0,
          "prob_home": 0.5772,
          "prob_draw": 0.2515,
          "prob_away": 0.1713
        },
        {
          "home_team": "Ecuador",
          "away_team": "Curaçao",
          "home_goals": 2,
          "away_goals": 0,
          "home_pts": 3,
          "away_pts": 0,
          "prob_home": 0.6979,
          "prob_draw": 0.2207,
          "prob_away": 0.0814
        },
        {
          "home_team": "Ecuador",
          "away_team": "Germany",
          "home_goals": 2,
          "away_goals": 1,
          "home_pts": 3,
          "away_pts": 0,
          "prob_home": 0.3653,
          "prob_draw": 0.3273,
          "prob_away": 0.3074
        },
        {
          "home_team": "Curaçao",
          "away_team": "Ivory Coast",
          "home_goals": 2,
          "away_goals": 1,
          "home_pts": 3,
          "away_pts": 0,
          "prob_home": 0.3438,
          "prob_draw": 0.3233,
          "prob_away": 0.3329
        }
      ],
      "table": [
        {
          "team": "Ecuador",
          "pts": 9,
          "gd": 4,
          "gf": 6,
          "ga": 2,
          "mp": 3,
          "w": 3,
          "d": 0,
          "l": 0
        },
        {
          "team": "Germany",
          "pts": 6,
          "gd": 2,
          "gf": 6,
          "ga": 4,
          "mp": 3,
          "w": 2,
          "d": 0,
          "l": 1
        },
        {
          "team": "Curaçao",
          "pts": 3,
          "gd": -3,
          "gf": 3,
          "ga": 6,
          "mp": 3,
          "w": 1,
          "d": 0,
          "l": 2
        },
        {
          "team": "Ivory Coast",
          "pts": 0,
          "gd": -3,
          "gf": 3,
          "ga": 6,
          "mp": 3,
          "w": 0,
          "d": 0,
          "l": 3
        }
      ]
    },
    {
      "group": "F",
      "matches": [
        {
          "home_team": "Netherlands",
          "away_team": "Japan",
          "home_goals": 2,
          "away_goals": 1,
          "home_pts": 3,
          "away_pts": 0,
          "prob_home": 0.4638,
          "prob_draw": 0.259,
          "prob_away": 0.2773
        },
        {
          "home_team": "Sweden",
          "away_team": "Tunisia",
          "home_goals": 2,
          "away_goals": 1,
          "home_pts": 3,
          "away_pts": 0,
          "prob_home": 0.4142,
          "prob_draw": 0.2943,
          "prob_away": 0.2915
        },
        {
          "home_team": "Netherlands",
          "away_team": "Sweden",
          "home_goals": 2,
          "away_goals": 1,
          "home_pts": 3,
          "away_pts": 0,
          "prob_home": 0.6616,
          "prob_draw": 0.1926,
          "prob_away": 0.1458
        },
        {
          "home_team": "Tunisia",
          "away_team": "Japan",
          "home_goals": 1,
          "away_goals": 2,
          "home_pts": 0,
          "away_pts": 3,
          "prob_home": 0.2167,
          "prob_draw": 0.3344,
          "prob_away": 0.449
        },
        {
          "home_team": "Japan",
          "away_team": "Sweden",
          "home_goals": 2,
          "away_goals": 1,
          "home_pts": 3,
          "away_pts": 0,
          "prob_home": 0.6868,
          "prob_draw": 0.2026,
          "prob_away": 0.1106
        },
        {
          "home_team": "Tunisia",
          "away_team": "Netherlands",
          "home_goals": 1,
          "away_goals": 2,
          "home_pts": 0,
          "away_pts": 3,
          "prob_home": 0.263,
          "prob_draw": 0.3135,
          "prob_away": 0.4235
        }
      ],
      "table": [
        {
          "team": "Netherlands",
          "pts": 9,
          "gd": 3,
          "gf": 6,
          "ga": 3,
          "mp": 3,
          "w": 3,
          "d": 0,
          "l": 0
        },
        {
          "team": "Japan",
          "pts": 6,
          "gd": 1,
          "gf": 5,
          "ga": 4,
          "mp": 3,
          "w": 2,
          "d": 0,
          "l": 1
        },
        {
          "team": "Sweden",
          "pts": 3,
          "gd": -1,
          "gf": 4,
          "ga": 5,
          "mp": 3,
          "w": 1,
          "d": 0,
          "l": 2
        },
        {
          "team": "Tunisia",
          "pts": 0,
          "gd": -3,
          "gf": 3,
          "ga": 6,
          "mp": 3,
          "w": 0,
          "d": 0,
          "l": 3
        }
      ]
    },
    {
      "group": "G",
      "matches": [
        {
          "home_team": "Iran",
          "away_team": "New Zealand",
          "home_goals": 2,
          "away_goals": 1,
          "home_pts": 3,
          "away_pts": 0,
          "prob_home": 0.5132,
          "prob_draw": 0.2566,
          "prob_away": 0.2301
        },
        {
          "home_team": "Belgium",
          "away_team": "Egypt",
          "home_goals": 2,
          "away_goals": 1,
          "home_pts": 3,
          "away_pts": 0,
          "prob_home": 0.4122,
          "prob_draw": 0.2789,
          "prob_away": 0.3089
        },
        {
          "home_team": "Belgium",
          "away_team": "Iran",
          "home_goals": 2,
          "away_goals": 1,
          "home_pts": 3,
          "away_pts": 0,
          "prob_home": 0.4851,
          "prob_draw": 0.2491,
          "prob_away": 0.2659
        },
        {
          "home_team": "New Zealand",
          "away_team": "Egypt",
          "home_goals": 2,
          "away_goals": 1,
          "home_pts": 3,
          "away_pts": 0,
          "prob_home": 0.3966,
          "prob_draw": 0.3141,
          "prob_away": 0.2893
        },
        {
          "home_team": "Egypt",
          "away_team": "Iran",
          "home_goals": 2,
          "away_goals": 1,
          "home_pts": 3,
          "away_pts": 0,
          "prob_home": 0.4087,
          "prob_draw": 0.2878,
          "prob_away": 0.3035
        },
        {
          "home_team": "New Zealand",
          "away_team": "Belgium",
          "home_goals": 1,
          "away_goals": 2,
          "home_pts": 0,
          "away_pts": 3,
          "prob_home": 0.3279,
          "prob_draw": 0.2899,
          "prob_away": 0.3822
        }
      ],
      "table": [
        {
          "team": "Belgium",
          "pts": 9,
          "gd": 3,
          "gf": 6,
          "ga": 3,
          "mp": 3,
          "w": 3,
          "d": 0,
          "l": 0
        },
        {
          "team": "Egypt",
          "pts": 3,
          "gd": -1,
          "gf": 4,
          "ga": 5,
          "mp": 3,
          "w": 1,
          "d": 0,
          "l": 2
        },
        {
          "team": "Iran",
          "pts": 3,
          "gd": -1,
          "gf": 4,
          "ga": 5,
          "mp": 3,
          "w": 1,
          "d": 0,
          "l": 2
        },
        {
          "team": "New Zealand",
          "pts": 3,
          "gd": -1,
          "gf": 4,
          "ga": 5,
          "mp": 3,
          "w": 1,
          "d": 0,
          "l": 2
        }
      ]
    },
    {
      "group": "H",
      "matches": [
        {
          "home_team": "Spain",
          "away_team": "Cape Verde",
          "home_goals": 3,
          "away_goals": 1,
          "home_pts": 3,
          "away_pts": 0,
          "prob_home": 0.8555,
          "prob_draw": 0.1039,
          "prob_away": 0.0406
        },
        {
          "home_team": "Saudi Arabia",
          "away_team": "Uruguay",
          "home_goals": 1,
          "away_goals": 2,
          "home_pts": 0,
          "away_pts": 3,
          "prob_home": 0.3273,
          "prob_draw": 0.2972,
          "prob_away": 0.3755
        },
        {
          "home_team": "Spain",
          "away_team": "Saudi Arabia",
          "home_goals": 3,
          "away_goals": 1,
          "home_pts": 3,
          "away_pts": 0,
          "prob_home": 0.8632,
          "prob_draw": 0.0991,
          "prob_away": 0.0377
        },
        {
          "home_team": "Uruguay",
          "away_team": "Cape Verde",
          "home_goals": 2,
          "away_goals": 0,
          "home_pts": 3,
          "away_pts": 0,
          "prob_home": 0.6676,
          "prob_draw": 0.2342,
          "prob_away": 0.0981
        },
        {
          "home_team": "Cape Verde",
          "away_team": "Saudi Arabia",
          "home_goals": 2,
          "away_goals": 1,
          "home_pts": 3,
          "away_pts": 0,
          "prob_home": 0.4538,
          "prob_draw": 0.3166,
          "prob_away": 0.2295
        },
        {
          "home_team": "Uruguay",
          "away_team": "Spain",
          "home_goals": 1,
          "away_goals": 2,
          "home_pts": 0,
          "away_pts": 3,
          "prob_home": 0.2843,
          "prob_draw": 0.3228,
          "prob_away": 0.3928
        }
      ],
      "table": [
        {
          "team": "Spain",
          "pts": 9,
          "gd": 5,
          "gf": 8,
          "ga": 3,
          "mp": 3,
          "w": 3,
          "d": 0,
          "l": 0
        },
        {
          "team": "Uruguay",
          "pts": 6,
          "gd": 2,
          "gf": 5,
          "ga": 3,
          "mp": 3,
          "w": 2,
          "d": 0,
          "l": 1
        },
        {
          "team": "Cape Verde",
          "pts": 3,
          "gd": -3,
          "gf": 3,
          "ga": 6,
          "mp": 3,
          "w": 1,
          "d": 0,
          "l": 2
        },
        {
          "team": "Saudi Arabia",
          "pts": 0,
          "gd": -4,
          "gf": 3,
          "ga": 7,
          "mp": 3,
          "w": 0,
          "d": 0,
          "l": 3
        }
      ]
    },
    {
      "group": "I",
      "matches": [
        {
          "home_team": "France",
          "away_team": "Senegal",
          "home_goals": 2,
          "away_goals": 1,
          "home_pts": 3,
          "away_pts": 0,
          "prob_home": 0.6471,
          "prob_draw": 0.2239,
          "prob_away": 0.129
        },
        {
          "home_team": "Iraq",
          "away_team": "Norway",
          "home_goals": 1,
          "away_goals": 2,
          "home_pts": 0,
          "away_pts": 3,
          "prob_home": 0.1927,
          "prob_draw": 0.2619,
          "prob_away": 0.5454
        },
        {
          "home_team": "France",
          "away_team": "Iraq",
          "home_goals": 3,
          "away_goals": 1,
          "home_pts": 3,
          "away_pts": 0,
          "prob_home": 0.8459,
          "prob_draw": 0.1091,
          "prob_away": 0.045
        },
        {
          "home_team": "Norway",
          "away_team": "Senegal",
          "home_goals": 2,
          "away_goals": 1,
          "home_pts": 3,
          "away_pts": 0,
          "prob_home": 0.4483,
          "prob_draw": 0.2641,
          "prob_away": 0.2876
        },
        {
          "home_team": "Norway",
          "away_team": "France",
          "home_goals": 1,
          "away_goals": 2,
          "home_pts": 0,
          "away_pts": 3,
          "prob_home": 0.1879,
          "prob_draw": 0.2298,
          "prob_away": 0.5823
        },
        {
          "home_team": "Senegal",
          "away_team": "Iraq",
          "home_goals": 2,
          "away_goals": 1,
          "home_pts": 3,
          "away_pts": 0,
          "prob_home": 0.5929,
          "prob_draw": 0.2514,
          "prob_away": 0.1557
        }
      ],
      "table": [
        {
          "team": "France",
          "pts": 9,
          "gd": 4,
          "gf": 7,
          "ga": 3,
          "mp": 3,
          "w": 3,
          "d": 0,
          "l": 0
        },
        {
          "team": "Norway",
          "pts": 6,
          "gd": 1,
          "gf": 5,
          "ga": 4,
          "mp": 3,
          "w": 2,
          "d": 0,
          "l": 1
        },
        {
          "team": "Senegal",
          "pts": 3,
          "gd": -1,
          "gf": 4,
          "ga": 5,
          "mp": 3,
          "w": 1,
          "d": 0,
          "l": 2
        },
        {
          "team": "Iraq",
          "pts": 0,
          "gd": -4,
          "gf": 3,
          "ga": 7,
          "mp": 3,
          "w": 0,
          "d": 0,
          "l": 3
        }
      ]
    },
    {
      "group": "J",
      "matches": [
        {
          "home_team": "Argentina",
          "away_team": "Algeria",
          "home_goals": 2,
          "away_goals": 1,
          "home_pts": 3,
          "away_pts": 0,
          "prob_home": 0.7543,
          "prob_draw": 0.1683,
          "prob_away": 0.0773
        },
        {
          "home_team": "Austria",
          "away_team": "Jordan",
          "home_goals": 2,
          "away_goals": 1,
          "home_pts": 3,
          "away_pts": 0,
          "prob_home": 0.5099,
          "prob_draw": 0.2642,
          "prob_away": 0.2259
        },
        {
          "home_team": "Argentina",
          "away_team": "Austria",
          "home_goals": 2,
          "away_goals": 1,
          "home_pts": 3,
          "away_pts": 0,
          "prob_home": 0.7079,
          "prob_draw": 0.1919,
          "prob_away": 0.1002
        },
        {
          "home_team": "Jordan",
          "away_team": "Algeria",
          "home_goals": 2,
          "away_goals": 1,
          "home_pts": 3,
          "away_pts": 0,
          "prob_home": 0.3842,
          "prob_draw": 0.2895,
          "prob_away": 0.3262
        },
        {
          "home_team": "Algeria",
          "away_team": "Austria",
          "home_goals": 2,
          "away_goals": 1,
          "home_pts": 3,
          "away_pts": 0,
          "prob_home": 0.4002,
          "prob_draw": 0.2823,
          "prob_away": 0.3175
        },
        {
          "home_team": "Jordan",
          "away_team": "Argentina",
          "home_goals": 1,
          "away_goals": 2,
          "home_pts": 0,
          "away_pts": 3,
          "prob_home": 0.2002,
          "prob_draw": 0.2614,
          "prob_away": 0.5384
        }
      ],
      "table": [
        {
          "team": "Argentina",
          "pts": 9,
          "gd": 3,
          "gf": 6,
          "ga": 3,
          "mp": 3,
          "w": 3,
          "d": 0,
          "l": 0
        },
        {
          "team": "Algeria",
          "pts": 3,
          "gd": -1,
          "gf": 4,
          "ga": 5,
          "mp": 3,
          "w": 1,
          "d": 0,
          "l": 2
        },
        {
          "team": "Austria",
          "pts": 3,
          "gd": -1,
          "gf": 4,
          "ga": 5,
          "mp": 3,
          "w": 1,
          "d": 0,
          "l": 2
        },
        {
          "team": "Jordan",
          "pts": 3,
          "gd": -1,
          "gf": 4,
          "ga": 5,
          "mp": 3,
          "w": 1,
          "d": 0,
          "l": 2
        }
      ]
    },
    {
      "group": "K",
      "matches": [
        {
          "home_team": "Portugal",
          "away_team": "DR Congo",
          "home_goals": 2,
          "away_goals": 1,
          "home_pts": 3,
          "away_pts": 0,
          "prob_home": 0.6608,
          "prob_draw": 0.2108,
          "prob_away": 0.1284
        },
        {
          "home_team": "Uzbekistan",
          "away_team": "Colombia",
          "home_goals": 1,
          "away_goals": 2,
          "home_pts": 0,
          "away_pts": 3,
          "prob_home": 0.2943,
          "prob_draw": 0.3432,
          "prob_away": 0.3625
        },
        {
          "home_team": "Portugal",
          "away_team": "Uzbekistan",
          "home_goals": 2,
          "away_goals": 1,
          "home_pts": 3,
          "away_pts": 0,
          "prob_home": 0.6146,
          "prob_draw": 0.2335,
          "prob_away": 0.1519
        },
        {
          "home_team": "Colombia",
          "away_team": "DR Congo",
          "home_goals": 2,
          "away_goals": 1,
          "home_pts": 3,
          "away_pts": 0,
          "prob_home": 0.5667,
          "prob_draw": 0.2828,
          "prob_away": 0.1504
        },
        {
          "home_team": "Colombia",
          "away_team": "Portugal",
          "home_goals": 2,
          "away_goals": 1,
          "home_pts": 3,
          "away_pts": 0,
          "prob_home": 0.4454,
          "prob_draw": 0.2744,
          "prob_away": 0.2802
        },
        {
          "home_team": "DR Congo",
          "away_team": "Uzbekistan",
          "home_goals": 2,
          "away_goals": 1,
          "home_pts": 3,
          "away_pts": 0,
          "prob_home": 0.385,
          "prob_draw": 0.3768,
          "prob_away": 0.2381
        }
      ],
      "table": [
        {
          "team": "Colombia",
          "pts": 9,
          "gd": 3,
          "gf": 6,
          "ga": 3,
          "mp": 3,
          "w": 3,
          "d": 0,
          "l": 0
        },
        {
          "team": "Portugal",
          "pts": 6,
          "gd": 1,
          "gf": 5,
          "ga": 4,
          "mp": 3,
          "w": 2,
          "d": 0,
          "l": 1
        },
        {
          "team": "DR Congo",
          "pts": 3,
          "gd": -1,
          "gf": 4,
          "ga": 5,
          "mp": 3,
          "w": 1,
          "d": 0,
          "l": 2
        },
        {
          "team": "Uzbekistan",
          "pts": 0,
          "gd": -3,
          "gf": 3,
          "ga": 6,
          "mp": 3,
          "w": 0,
          "d": 0,
          "l": 3
        }
      ]
    },
    {
      "group": "L",
      "matches": [
        {
          "home_team": "England",
          "away_team": "Croatia",
          "home_goals": 2,
          "away_goals": 1,
          "home_pts": 3,
          "away_pts": 0,
          "prob_home": 0.5961,
          "prob_draw": 0.2493,
          "prob_away": 0.1546
        },
        {
          "home_team": "Ghana",
          "away_team": "Panama",
          "home_goals": 2,
          "away_goals": 1,
          "home_pts": 3,
          "away_pts": 0,
          "prob_home": 0.4473,
          "prob_draw": 0.2828,
          "prob_away": 0.2698
        },
        {
          "home_team": "England",
          "away_team": "Ghana",
          "home_goals": 3,
          "away_goals": 1,
          "home_pts": 3,
          "away_pts": 0,
          "prob_home": 0.8518,
          "prob_draw": 0.1086,
          "prob_away": 0.0396
        },
        {
          "home_team": "Panama",
          "away_team": "Croatia",
          "home_goals": 1,
          "away_goals": 2,
          "home_pts": 0,
          "away_pts": 3,
          "prob_home": 0.2707,
          "prob_draw": 0.2789,
          "prob_away": 0.4504
        },
        {
          "home_team": "Panama",
          "away_team": "England",
          "home_goals": 1,
          "away_goals": 2,
          "home_pts": 0,
          "away_pts": 3,
          "prob_home": 0.1889,
          "prob_draw": 0.3052,
          "prob_away": 0.5059
        },
        {
          "home_team": "Croatia",
          "away_team": "Ghana",
          "home_goals": 2,
          "away_goals": 1,
          "home_pts": 3,
          "away_pts": 0,
          "prob_home": 0.559,
          "prob_draw": 0.2606,
          "prob_away": 0.1804
        }
      ],
      "table": [
        {
          "team": "England",
          "pts": 9,
          "gd": 4,
          "gf": 7,
          "ga": 3,
          "mp": 3,
          "w": 3,
          "d": 0,
          "l": 0
        },
        {
          "team": "Croatia",
          "pts": 6,
          "gd": 1,
          "gf": 5,
          "ga": 4,
          "mp": 3,
          "w": 2,
          "d": 0,
          "l": 1
        },
        {
          "team": "Ghana",
          "pts": 3,
          "gd": -2,
          "gf": 4,
          "ga": 6,
          "mp": 3,
          "w": 1,
          "d": 0,
          "l": 2
        },
        {
          "team": "Panama",
          "pts": 0,
          "gd": -3,
          "gf": 3,
          "ga": 6,
          "mp": 3,
          "w": 0,
          "d": 0,
          "l": 3
        }
      ]
    }
  ],
  "best_thirds": {
    "A": "Czech Republic",
    "B": "Bosnia and Herzegovina",
    "C": "Scotland",
    "D": "Paraguay",
    "F": "Sweden",
    "G": "Iran",
    "I": "Senegal",
    "J": "Austria"
  },
  "knockout": {
    "r32": [
      {
        "team1": "South Korea",
        "team2": "Canada",
        "team1_goals": 2,
        "team2_goals": 1,
        "winner": "South Korea",
        "penalties": false,
        "prob_team1": 0.4472,
        "prob_draw": 0.3176,
        "prob_team2": 0.2352
      },
      {
        "team1": "Ecuador",
        "team2": "Paraguay",
        "team1_goals": 2,
        "team2_goals": 1,
        "winner": "Ecuador",
        "penalties": false,
        "prob_team1": 0.5252,
        "prob_draw": 0.3188,
        "prob_team2": 0.1561
      },
      {
        "team1": "Netherlands",
        "team2": "Morocco",
        "team1_goals": 2,
        "team2_goals": 1,
        "winner": "Netherlands",
        "penalties": false,
        "prob_team1": 0.5266,
        "prob_draw": 0.2663,
        "prob_team2": 0.207
      },
      {
        "team1": "Brazil",
        "team2": "Japan",
        "team1_goals": 2,
        "team2_goals": 1,
        "winner": "Brazil",
        "penalties": false,
        "prob_team1": 0.5467,
        "prob_draw": 0.2575,
        "prob_team2": 0.1958
      },
      {
        "team1": "France",
        "team2": "Sweden",
        "team1_goals": 2,
        "team2_goals": 1,
        "winner": "France",
        "penalties": false,
        "prob_team1": 0.7346,
        "prob_draw": 0.1683,
        "prob_team2": 0.0972
      },
      {
        "team1": "Germany",
        "team2": "Norway",
        "team1_goals": 2,
        "team2_goals": 1,
        "winner": "Germany",
        "penalties": false,
        "prob_team1": 0.543,
        "prob_draw": 0.2173,
        "prob_team2": 0.2397
      },
      {
        "team1": "Mexico",
        "team2": "Scotland",
        "team1_goals": 2,
        "team2_goals": 1,
        "winner": "Mexico",
        "penalties": false,
        "prob_team1": 0.567,
        "prob_draw": 0.2909,
        "prob_team2": 0.1421
      },
      {
        "team1": "England",
        "team2": "Austria",
        "team1_goals": 2,
        "team2_goals": 1,
        "winner": "England",
        "penalties": false,
        "prob_team1": 0.6209,
        "prob_draw": 0.2419,
        "prob_team2": 0.1372
      },
      {
        "team1": "United States",
        "team2": "Bosnia and Herzegovina",
        "team1_goals": 2,
        "team2_goals": 1,
        "winner": "United States",
        "penalties": false,
        "prob_team1": 0.7594,
        "prob_draw": 0.1632,
        "prob_team2": 0.0773
      },
      {
        "team1": "Belgium",
        "team2": "Czech Republic",
        "team1_goals": 2,
        "team2_goals": 1,
        "winner": "Belgium",
        "penalties": false,
        "prob_team1": 0.5879,
        "prob_draw": 0.237,
        "prob_team2": 0.1751
      },
      {
        "team1": "Portugal",
        "team2": "Croatia",
        "team1_goals": 2,
        "team2_goals": 1,
        "winner": "Portugal",
        "penalties": false,
        "prob_team1": 0.64,
        "prob_draw": 0.2014,
        "prob_team2": 0.1585
      },
      {
        "team1": "Spain",
        "team2": "Algeria",
        "team1_goals": 3,
        "team2_goals": 1,
        "winner": "Spain",
        "penalties": false,
        "prob_team1": 0.7959,
        "prob_draw": 0.136,
        "prob_team2": 0.0681
      },
      {
        "team1": "Switzerland",
        "team2": "Iran",
        "team1_goals": 2,
        "team2_goals": 1,
        "winner": "Switzerland",
        "penalties": false,
        "prob_team1": 0.5244,
        "prob_draw": 0.2524,
        "prob_team2": 0.2231
      },
      {
        "team1": "Argentina",
        "team2": "Uruguay",
        "team1_goals": 1,
        "team2_goals": 0,
        "winner": "Argentina",
        "penalties": false,
        "prob_team1": 0.5432,
        "prob_draw": 0.3162,
        "prob_team2": 0.1407
      },
      {
        "team1": "Colombia",
        "team2": "Senegal",
        "team1_goals": 2,
        "team2_goals": 1,
        "winner": "Colombia",
        "penalties": false,
        "prob_team1": 0.5152,
        "prob_draw": 0.3055,
        "prob_team2": 0.1793
      },
      {
        "team1": "Turkey",
        "team2": "Egypt",
        "team1_goals": 2,
        "team2_goals": 1,
        "winner": "Turkey",
        "penalties": false,
        "prob_team1": 0.3989,
        "prob_draw": 0.2538,
        "prob_team2": 0.3473
      }
    ],
    "r16": [
      {
        "team1": "Ecuador",
        "team2": "France",
        "team1_goals": 1,
        "team2_goals": 2,
        "winner": "France",
        "penalties": false,
        "prob_team1": 0.1724,
        "prob_draw": 0.299,
        "prob_team2": 0.5286
      },
      {
        "team1": "South Korea",
        "team2": "Netherlands",
        "team1_goals": 1,
        "team2_goals": 2,
        "winner": "Netherlands",
        "penalties": false,
        "prob_team1": 0.3381,
        "prob_draw": 0.2865,
        "prob_team2": 0.3753
      },
      {
        "team1": "Brazil",
        "team2": "Germany",
        "team1_goals": 2,
        "team2_goals": 1,
        "winner": "Brazil",
        "penalties": false,
        "prob_team1": 0.5454,
        "prob_draw": 0.2417,
        "prob_team2": 0.2129
      },
      {
        "team1": "Mexico",
        "team2": "England",
        "team1_goals": 1,
        "team2_goals": 2,
        "winner": "England",
        "penalties": false,
        "prob_team1": 0.2955,
        "prob_draw": 0.3452,
        "prob_team2": 0.3593
      },
      {
        "team1": "Portugal",
        "team2": "Spain",
        "team1_goals": 1,
        "team2_goals": 2,
        "winner": "Spain",
        "penalties": false,
        "prob_team1": 0.3131,
        "prob_draw": 0.2513,
        "prob_team2": 0.4356
      },
      {
        "team1": "United States",
        "team2": "Belgium",
        "team1_goals": 2,
        "team2_goals": 1,
        "winner": "United States",
        "penalties": false,
        "prob_team1": 0.365,
        "prob_draw": 0.2964,
        "prob_team2": 0.3386
      },
      {
        "team1": "Argentina",
        "team2": "Turkey",
        "team1_goals": 2,
        "team2_goals": 1,
        "winner": "Argentina",
        "penalties": false,
        "prob_team1": 0.7023,
        "prob_draw": 0.1893,
        "prob_team2": 0.1083
      },
      {
        "team1": "Switzerland",
        "team2": "Colombia",
        "team1_goals": 1,
        "team2_goals": 2,
        "winner": "Colombia",
        "penalties": false,
        "prob_team1": 0.3394,
        "prob_draw": 0.2855,
        "prob_team2": 0.3752
      }
    ],
    "qf": [
      {
        "team1": "France",
        "team2": "Netherlands",
        "team1_goals": 2,
        "team2_goals": 1,
        "winner": "France",
        "penalties": false,
        "prob_team1": 0.5736,
        "prob_draw": 0.2237,
        "prob_team2": 0.2027
      },
      {
        "team1": "Spain",
        "team2": "United States",
        "team1_goals": 2,
        "team2_goals": 1,
        "winner": "Spain",
        "penalties": false,
        "prob_team1": 0.759,
        "prob_draw": 0.163,
        "prob_team2": 0.078
      },
      {
        "team1": "Brazil",
        "team2": "England",
        "team1_goals": 2,
        "team2_goals": 1,
        "winner": "Brazil",
        "penalties": false,
        "prob_team1": 0.37,
        "prob_draw": 0.3365,
        "prob_team2": 0.2935
      },
      {
        "team1": "Argentina",
        "team2": "Colombia",
        "team1_goals": 2,
        "team2_goals": 1,
        "winner": "Argentina",
        "penalties": false,
        "prob_team1": 0.5119,
        "prob_draw": 0.3076,
        "prob_team2": 0.1805
      }
    ],
    "sf": [
      {
        "team1": "France",
        "team2": "Spain",
        "team1_goals": 2,
        "team2_goals": 1,
        "winner": "France",
        "penalties": false,
        "prob_team1": 0.4153,
        "prob_draw": 0.2739,
        "prob_team2": 0.3108
      },
      {
        "team1": "Brazil",
        "team2": "Argentina",
        "team1_goals": 1,
        "team2_goals": 2,
        "winner": "Argentina",
        "penalties": false,
        "prob_team1": 0.2062,
        "prob_draw": 0.327,
        "prob_team2": 0.4668
      }
    ],
    "final": [
      {
        "team1": "France",
        "team2": "Argentina",
        "team1_goals": 2,
        "team2_goals": 1,
        "winner": "France",
        "penalties": false,
        "prob_team1": 0.4254,
        "prob_draw": 0.2796,
        "prob_team2": 0.2951
      }
    ]
  }
};
