/**
 * Pre-computed deterministic prediction results.
 * Generated by notebooks/phase2/07_deterministic_prediction.ipynb
 *
 * This is the model's single best answer — argmax of predicted probabilities
 * for every match. Unlike Monte Carlo simulation, this always produces the
 * same result: France wins the 2026 World Cup.
 */

/* ── types (mirrors the API response shape) ── */

interface ApiGroupMatch {
  home_team: string;
  away_team: string;
  home_goals: number;
  away_goals: number;
  home_pts: number;
  away_pts: number;
  prob_home: number;
  prob_draw: number;
  prob_away: number;
}

interface ApiGroupTeam {
  team: string;
  pts: number;
  gd: number;
  gf: number;
  ga: number;
  mp: number;
  w: number;
  d: number;
  l: number;
}

interface ApiGroup {
  group: string;
  matches: ApiGroupMatch[];
  table: ApiGroupTeam[];
}

interface ApiKnockoutMatch {
  team1: string;
  team2: string;
  team1_goals: number;
  team2_goals: number;
  winner: string;
  penalties: boolean;
  prob_team1: number;
  prob_draw: number;
  prob_team2: number;
}

export interface DeterministicData {
  champion: string;
  groups: ApiGroup[];
  best_thirds: Record<string, string>;
  knockout: Record<string, ApiKnockoutMatch[]>;
}

/* ── group matches by group ── */

const GROUP_MATCHES: Record<string, ApiGroupMatch[]> = {
  A: [
    { home_team: "Mexico", away_team: "South Africa", home_goals: 2, away_goals: 0, home_pts: 3, away_pts: 0, prob_home: 0.817, prob_draw: 0.15, prob_away: 0.033 },
    { home_team: "South Korea", away_team: "Czech Republic", home_goals: 0, away_goals: 0, home_pts: 1, away_pts: 1, prob_home: 0.365, prob_draw: 0.407, prob_away: 0.228 },
    { home_team: "Czech Republic", away_team: "South Africa", home_goals: 1, away_goals: 0, home_pts: 3, away_pts: 0, prob_home: 0.666, prob_draw: 0.218, prob_away: 0.116 },
    { home_team: "Mexico", away_team: "South Korea", home_goals: 1, away_goals: 0, home_pts: 3, away_pts: 0, prob_home: 0.501, prob_draw: 0.309, prob_away: 0.19 },
    { home_team: "Czech Republic", away_team: "Mexico", home_goals: 0, away_goals: 1, home_pts: 0, away_pts: 3, prob_home: 0.365, prob_draw: 0.267, prob_away: 0.368 },
    { home_team: "South Africa", away_team: "South Korea", home_goals: 0, away_goals: 1, home_pts: 0, away_pts: 3, prob_home: 0.217, prob_draw: 0.259, prob_away: 0.524 },
  ],
  B: [
    { home_team: "Canada", away_team: "Bosnia and Herzegovina", home_goals: 1, away_goals: 0, home_pts: 3, away_pts: 0, prob_home: 0.687, prob_draw: 0.207, prob_away: 0.106 },
    { home_team: "Qatar", away_team: "Switzerland", home_goals: 0, away_goals: 2, home_pts: 0, away_pts: 3, prob_home: 0.1, prob_draw: 0.187, prob_away: 0.713 },
    { home_team: "Switzerland", away_team: "Bosnia and Herzegovina", home_goals: 1, away_goals: 0, home_pts: 3, away_pts: 0, prob_home: 0.757, prob_draw: 0.18, prob_away: 0.063 },
    { home_team: "Canada", away_team: "Qatar", home_goals: 2, away_goals: 0, home_pts: 3, away_pts: 0, prob_home: 0.808, prob_draw: 0.147, prob_away: 0.044 },
    { home_team: "Switzerland", away_team: "Canada", home_goals: 1, away_goals: 0, home_pts: 3, away_pts: 0, prob_home: 0.628, prob_draw: 0.23, prob_away: 0.141 },
    { home_team: "Bosnia and Herzegovina", away_team: "Qatar", home_goals: 1, away_goals: 0, home_pts: 3, away_pts: 0, prob_home: 0.58, prob_draw: 0.237, prob_away: 0.183 },
  ],
  C: [
    { home_team: "Brazil", away_team: "Morocco", home_goals: 1, away_goals: 0, home_pts: 3, away_pts: 0, prob_home: 0.648, prob_draw: 0.23, prob_away: 0.121 },
    { home_team: "Haiti", away_team: "Scotland", home_goals: 0, away_goals: 1, home_pts: 0, away_pts: 3, prob_home: 0.246, prob_draw: 0.268, prob_away: 0.486 },
    { home_team: "Scotland", away_team: "Morocco", home_goals: 1, away_goals: 0, home_pts: 3, away_pts: 0, prob_home: 0.379, prob_draw: 0.331, prob_away: 0.29 },
    { home_team: "Brazil", away_team: "Haiti", home_goals: 2, away_goals: 0, home_pts: 3, away_pts: 0, prob_home: 0.874, prob_draw: 0.105, prob_away: 0.021 },
    { home_team: "Scotland", away_team: "Brazil", home_goals: 0, away_goals: 1, home_pts: 0, away_pts: 3, prob_home: 0.19, prob_draw: 0.313, prob_away: 0.496 },
    { home_team: "Morocco", away_team: "Haiti", home_goals: 1, away_goals: 0, home_pts: 3, away_pts: 0, prob_home: 0.701, prob_draw: 0.24, prob_away: 0.059 },
  ],
  D: [
    { home_team: "United States", away_team: "Paraguay", home_goals: 1, away_goals: 0, home_pts: 3, away_pts: 0, prob_home: 0.442, prob_draw: 0.254, prob_away: 0.304 },
    { home_team: "Australia", away_team: "Turkey", home_goals: 0, away_goals: 1, home_pts: 0, away_pts: 3, prob_home: 0.208, prob_draw: 0.293, prob_away: 0.499 },
    { home_team: "United States", away_team: "Australia", home_goals: 1, away_goals: 0, home_pts: 3, away_pts: 0, prob_home: 0.481, prob_draw: 0.265, prob_away: 0.254 },
    { home_team: "Turkey", away_team: "Paraguay", home_goals: 2, away_goals: 0, home_pts: 3, away_pts: 0, prob_home: 0.622, prob_draw: 0.205, prob_away: 0.172 },
    { home_team: "Turkey", away_team: "United States", home_goals: 1, away_goals: 0, home_pts: 3, away_pts: 0, prob_home: 0.617, prob_draw: 0.24, prob_away: 0.143 },
    { home_team: "Paraguay", away_team: "Australia", home_goals: 1, away_goals: 0, home_pts: 3, away_pts: 0, prob_home: 0.529, prob_draw: 0.263, prob_away: 0.208 },
  ],
  E: [
    { home_team: "Germany", away_team: "Curaçao", home_goals: 2, away_goals: 0, home_pts: 3, away_pts: 0, prob_home: 0.8, prob_draw: 0.155, prob_away: 0.045 },
    { home_team: "Ivory Coast", away_team: "Ecuador", home_goals: 0, away_goals: 1, home_pts: 0, away_pts: 3, prob_home: 0.341, prob_draw: 0.283, prob_away: 0.376 },
    { home_team: "Germany", away_team: "Ivory Coast", home_goals: 2, away_goals: 0, home_pts: 3, away_pts: 0, prob_home: 0.769, prob_draw: 0.161, prob_away: 0.07 },
    { home_team: "Ecuador", away_team: "Curaçao", home_goals: 1, away_goals: 0, home_pts: 3, away_pts: 0, prob_home: 0.709, prob_draw: 0.235, prob_away: 0.055 },
    { home_team: "Ecuador", away_team: "Germany", home_goals: 0, away_goals: 1, home_pts: 0, away_pts: 3, prob_home: 0.309, prob_draw: 0.332, prob_away: 0.36 },
    { home_team: "Curaçao", away_team: "Ivory Coast", home_goals: 1, away_goals: 0, home_pts: 3, away_pts: 0, prob_home: 0.403, prob_draw: 0.263, prob_away: 0.335 },
  ],
  F: [
    { home_team: "Netherlands", away_team: "Japan", home_goals: 2, away_goals: 0, home_pts: 3, away_pts: 0, prob_home: 0.673, prob_draw: 0.193, prob_away: 0.134 },
    { home_team: "Sweden", away_team: "Tunisia", home_goals: 1, away_goals: 0, home_pts: 3, away_pts: 0, prob_home: 0.627, prob_draw: 0.222, prob_away: 0.15 },
    { home_team: "Netherlands", away_team: "Sweden", home_goals: 1, away_goals: 0, home_pts: 3, away_pts: 0, prob_home: 0.708, prob_draw: 0.189, prob_away: 0.104 },
    { home_team: "Tunisia", away_team: "Japan", home_goals: 0, away_goals: 1, home_pts: 0, away_pts: 3, prob_home: 0.197, prob_draw: 0.296, prob_away: 0.508 },
    { home_team: "Japan", away_team: "Sweden", home_goals: 1, away_goals: 0, home_pts: 3, away_pts: 0, prob_home: 0.548, prob_draw: 0.266, prob_away: 0.186 },
    { home_team: "Tunisia", away_team: "Netherlands", home_goals: 0, away_goals: 2, home_pts: 0, away_pts: 3, prob_home: 0.157, prob_draw: 0.202, prob_away: 0.641 },
  ],
  G: [
    { home_team: "Iran", away_team: "New Zealand", home_goals: 1, away_goals: 0, home_pts: 3, away_pts: 0, prob_home: 0.438, prob_draw: 0.329, prob_away: 0.234 },
    { home_team: "Belgium", away_team: "Egypt", home_goals: 1, away_goals: 0, home_pts: 3, away_pts: 0, prob_home: 0.603, prob_draw: 0.211, prob_away: 0.186 },
    { home_team: "Belgium", away_team: "Iran", home_goals: 2, away_goals: 0, home_pts: 3, away_pts: 0, prob_home: 0.654, prob_draw: 0.191, prob_away: 0.156 },
    { home_team: "New Zealand", away_team: "Egypt", home_goals: 0, away_goals: 1, home_pts: 0, away_pts: 3, prob_home: 0.366, prob_draw: 0.248, prob_away: 0.385 },
    { home_team: "Egypt", away_team: "Iran", home_goals: 1, away_goals: 0, home_pts: 3, away_pts: 0, prob_home: 0.412, prob_draw: 0.289, prob_away: 0.299 },
    { home_team: "New Zealand", away_team: "Belgium", home_goals: 0, away_goals: 1, home_pts: 0, away_pts: 3, prob_home: 0.206, prob_draw: 0.239, prob_away: 0.555 },
  ],
  H: [
    { home_team: "Spain", away_team: "Cape Verde", home_goals: 2, away_goals: 0, home_pts: 3, away_pts: 0, prob_home: 0.828, prob_draw: 0.132, prob_away: 0.04 },
    { home_team: "Saudi Arabia", away_team: "Uruguay", home_goals: 0, away_goals: 1, home_pts: 0, away_pts: 3, prob_home: 0.21, prob_draw: 0.255, prob_away: 0.535 },
    { home_team: "Spain", away_team: "Saudi Arabia", home_goals: 2, away_goals: 0, home_pts: 3, away_pts: 0, prob_home: 0.854, prob_draw: 0.11, prob_away: 0.036 },
    { home_team: "Uruguay", away_team: "Cape Verde", home_goals: 2, away_goals: 0, home_pts: 3, away_pts: 0, prob_home: 0.769, prob_draw: 0.175, prob_away: 0.055 },
    { home_team: "Cape Verde", away_team: "Saudi Arabia", home_goals: 1, away_goals: 0, home_pts: 3, away_pts: 0, prob_home: 0.47, prob_draw: 0.273, prob_away: 0.257 },
    { home_team: "Uruguay", away_team: "Spain", home_goals: 0, away_goals: 1, home_pts: 0, away_pts: 3, prob_home: 0.221, prob_draw: 0.316, prob_away: 0.463 },
  ],
  I: [
    { home_team: "France", away_team: "Senegal", home_goals: 1, away_goals: 0, home_pts: 3, away_pts: 0, prob_home: 0.686, prob_draw: 0.21, prob_away: 0.103 },
    { home_team: "Iraq", away_team: "Norway", home_goals: 0, away_goals: 1, home_pts: 0, away_pts: 3, prob_home: 0.173, prob_draw: 0.229, prob_away: 0.598 },
    { home_team: "France", away_team: "Iraq", home_goals: 2, away_goals: 0, home_pts: 3, away_pts: 0, prob_home: 0.795, prob_draw: 0.154, prob_away: 0.051 },
    { home_team: "Norway", away_team: "Senegal", home_goals: 2, away_goals: 1, home_pts: 3, away_pts: 0, prob_home: 0.602, prob_draw: 0.201, prob_away: 0.197 },
    { home_team: "Norway", away_team: "France", home_goals: 1, away_goals: 2, home_pts: 0, away_pts: 3, prob_home: 0.305, prob_draw: 0.233, prob_away: 0.462 },
    { home_team: "Senegal", away_team: "Iraq", home_goals: 1, away_goals: 0, home_pts: 3, away_pts: 0, prob_home: 0.751, prob_draw: 0.181, prob_away: 0.068 },
  ],
  J: [
    { home_team: "Argentina", away_team: "Algeria", home_goals: 1, away_goals: 0, home_pts: 3, away_pts: 0, prob_home: 0.759, prob_draw: 0.179, prob_away: 0.062 },
    { home_team: "Austria", away_team: "Jordan", home_goals: 2, away_goals: 0, home_pts: 3, away_pts: 0, prob_home: 0.679, prob_draw: 0.187, prob_away: 0.134 },
    { home_team: "Argentina", away_team: "Austria", home_goals: 1, away_goals: 0, home_pts: 3, away_pts: 0, prob_home: 0.688, prob_draw: 0.232, prob_away: 0.08 },
    { home_team: "Jordan", away_team: "Algeria", home_goals: 0, away_goals: 1, home_pts: 0, away_pts: 3, prob_home: 0.362, prob_draw: 0.269, prob_away: 0.369 },
    { home_team: "Algeria", away_team: "Austria", home_goals: 1, away_goals: 0, home_pts: 3, away_pts: 0, prob_home: 0.38, prob_draw: 0.292, prob_away: 0.328 },
    { home_team: "Jordan", away_team: "Argentina", home_goals: 0, away_goals: 2, home_pts: 0, away_pts: 3, prob_home: 0.134, prob_draw: 0.2, prob_away: 0.666 },
  ],
  K: [
    { home_team: "Portugal", away_team: "DR Congo", home_goals: 1, away_goals: 0, home_pts: 3, away_pts: 0, prob_home: 0.739, prob_draw: 0.184, prob_away: 0.077 },
    { home_team: "Uzbekistan", away_team: "Colombia", home_goals: 0, away_goals: 1, home_pts: 0, away_pts: 3, prob_home: 0.278, prob_draw: 0.293, prob_away: 0.429 },
    { home_team: "Portugal", away_team: "Uzbekistan", home_goals: 2, away_goals: 0, home_pts: 3, away_pts: 0, prob_home: 0.729, prob_draw: 0.177, prob_away: 0.094 },
    { home_team: "Colombia", away_team: "DR Congo", home_goals: 1, away_goals: 0, home_pts: 3, away_pts: 0, prob_home: 0.726, prob_draw: 0.199, prob_away: 0.075 },
    { home_team: "Colombia", away_team: "Portugal", home_goals: 1, away_goals: 0, home_pts: 3, away_pts: 0, prob_home: 0.412, prob_draw: 0.259, prob_away: 0.33 },
    { home_team: "DR Congo", away_team: "Uzbekistan", home_goals: 1, away_goals: 0, home_pts: 3, away_pts: 0, prob_home: 0.386, prob_draw: 0.337, prob_away: 0.277 },
  ],
  L: [
    { home_team: "England", away_team: "Croatia", home_goals: 1, away_goals: 0, home_pts: 3, away_pts: 0, prob_home: 0.682, prob_draw: 0.204, prob_away: 0.114 },
    { home_team: "Ghana", away_team: "Panama", home_goals: 2, away_goals: 1, home_pts: 3, away_pts: 0, prob_home: 0.413, prob_draw: 0.24, prob_away: 0.347 },
    { home_team: "England", away_team: "Ghana", home_goals: 1, away_goals: 0, home_pts: 3, away_pts: 0, prob_home: 0.711, prob_draw: 0.214, prob_away: 0.075 },
    { home_team: "Panama", away_team: "Croatia", home_goals: 0, away_goals: 1, home_pts: 0, away_pts: 3, prob_home: 0.232, prob_draw: 0.269, prob_away: 0.499 },
    { home_team: "Panama", away_team: "England", home_goals: 0, away_goals: 2, home_pts: 0, away_pts: 3, prob_home: 0.158, prob_draw: 0.2, prob_away: 0.642 },
    { home_team: "Croatia", away_team: "Ghana", home_goals: 1, away_goals: 0, home_pts: 3, away_pts: 0, prob_home: 0.697, prob_draw: 0.22, prob_away: 0.083 },
  ],
};

/* ── group tables (final standings) ── */

const GROUP_TABLES: Record<string, ApiGroupTeam[]> = {
  A: [
    { team: "Mexico", pts: 9, gd: 4, gf: 4, ga: 0, mp: 3, w: 3, d: 0, l: 0 },
    { team: "South Korea", pts: 4, gd: 0, gf: 1, ga: 1, mp: 3, w: 1, d: 1, l: 1 },
    { team: "Czech Republic", pts: 4, gd: 0, gf: 1, ga: 1, mp: 3, w: 1, d: 1, l: 1 },
    { team: "South Africa", pts: 0, gd: -4, gf: 0, ga: 4, mp: 3, w: 0, d: 0, l: 3 },
  ],
  B: [
    { team: "Switzerland", pts: 9, gd: 4, gf: 4, ga: 0, mp: 3, w: 3, d: 0, l: 0 },
    { team: "Canada", pts: 6, gd: 2, gf: 3, ga: 1, mp: 3, w: 2, d: 0, l: 1 },
    { team: "Bosnia and Herzegovina", pts: 3, gd: -1, gf: 1, ga: 2, mp: 3, w: 1, d: 0, l: 2 },
    { team: "Qatar", pts: 0, gd: -5, gf: 0, ga: 5, mp: 3, w: 0, d: 0, l: 3 },
  ],
  C: [
    { team: "Brazil", pts: 9, gd: 4, gf: 4, ga: 0, mp: 3, w: 3, d: 0, l: 0 },
    { team: "Scotland", pts: 6, gd: 1, gf: 2, ga: 1, mp: 3, w: 2, d: 0, l: 1 },
    { team: "Morocco", pts: 3, gd: -1, gf: 1, ga: 2, mp: 3, w: 1, d: 0, l: 2 },
    { team: "Haiti", pts: 0, gd: -4, gf: 0, ga: 4, mp: 3, w: 0, d: 0, l: 3 },
  ],
  D: [
    { team: "Turkey", pts: 9, gd: 4, gf: 4, ga: 0, mp: 3, w: 3, d: 0, l: 0 },
    { team: "United States", pts: 6, gd: 1, gf: 2, ga: 1, mp: 3, w: 2, d: 0, l: 1 },
    { team: "Paraguay", pts: 3, gd: -2, gf: 1, ga: 3, mp: 3, w: 1, d: 0, l: 2 },
    { team: "Australia", pts: 0, gd: -3, gf: 0, ga: 3, mp: 3, w: 0, d: 0, l: 3 },
  ],
  E: [
    { team: "Germany", pts: 9, gd: 5, gf: 5, ga: 0, mp: 3, w: 3, d: 0, l: 0 },
    { team: "Ecuador", pts: 6, gd: 1, gf: 2, ga: 1, mp: 3, w: 2, d: 0, l: 1 },
    { team: "Curaçao", pts: 3, gd: -2, gf: 1, ga: 3, mp: 3, w: 1, d: 0, l: 2 },
    { team: "Ivory Coast", pts: 0, gd: -4, gf: 0, ga: 4, mp: 3, w: 0, d: 0, l: 3 },
  ],
  F: [
    { team: "Netherlands", pts: 9, gd: 5, gf: 5, ga: 0, mp: 3, w: 3, d: 0, l: 0 },
    { team: "Japan", pts: 6, gd: 0, gf: 2, ga: 2, mp: 3, w: 2, d: 0, l: 1 },
    { team: "Sweden", pts: 3, gd: -1, gf: 1, ga: 2, mp: 3, w: 1, d: 0, l: 2 },
    { team: "Tunisia", pts: 0, gd: -4, gf: 0, ga: 4, mp: 3, w: 0, d: 0, l: 3 },
  ],
  G: [
    { team: "Belgium", pts: 9, gd: 4, gf: 4, ga: 0, mp: 3, w: 3, d: 0, l: 0 },
    { team: "Egypt", pts: 6, gd: 1, gf: 2, ga: 1, mp: 3, w: 2, d: 0, l: 1 },
    { team: "Iran", pts: 3, gd: -2, gf: 1, ga: 3, mp: 3, w: 1, d: 0, l: 2 },
    { team: "New Zealand", pts: 0, gd: -3, gf: 0, ga: 3, mp: 3, w: 0, d: 0, l: 3 },
  ],
  H: [
    { team: "Spain", pts: 9, gd: 5, gf: 5, ga: 0, mp: 3, w: 3, d: 0, l: 0 },
    { team: "Uruguay", pts: 6, gd: 2, gf: 3, ga: 1, mp: 3, w: 2, d: 0, l: 1 },
    { team: "Cape Verde", pts: 3, gd: -3, gf: 1, ga: 4, mp: 3, w: 1, d: 0, l: 2 },
    { team: "Saudi Arabia", pts: 0, gd: -4, gf: 0, ga: 4, mp: 3, w: 0, d: 0, l: 3 },
  ],
  I: [
    { team: "France", pts: 9, gd: 4, gf: 5, ga: 1, mp: 3, w: 3, d: 0, l: 0 },
    { team: "Norway", pts: 6, gd: 1, gf: 4, ga: 3, mp: 3, w: 2, d: 0, l: 1 },
    { team: "Senegal", pts: 3, gd: -1, gf: 2, ga: 3, mp: 3, w: 1, d: 0, l: 2 },
    { team: "Iraq", pts: 0, gd: -4, gf: 0, ga: 4, mp: 3, w: 0, d: 0, l: 3 },
  ],
  J: [
    { team: "Argentina", pts: 9, gd: 4, gf: 4, ga: 0, mp: 3, w: 3, d: 0, l: 0 },
    { team: "Algeria", pts: 6, gd: 1, gf: 2, ga: 1, mp: 3, w: 2, d: 0, l: 1 },
    { team: "Austria", pts: 3, gd: 0, gf: 2, ga: 2, mp: 3, w: 1, d: 0, l: 2 },
    { team: "Jordan", pts: 0, gd: -5, gf: 0, ga: 5, mp: 3, w: 0, d: 0, l: 3 },
  ],
  K: [
    { team: "Colombia", pts: 9, gd: 3, gf: 3, ga: 0, mp: 3, w: 3, d: 0, l: 0 },
    { team: "Portugal", pts: 6, gd: 2, gf: 3, ga: 1, mp: 3, w: 2, d: 0, l: 1 },
    { team: "DR Congo", pts: 3, gd: -1, gf: 1, ga: 2, mp: 3, w: 1, d: 0, l: 2 },
    { team: "Uzbekistan", pts: 0, gd: -4, gf: 0, ga: 4, mp: 3, w: 0, d: 0, l: 3 },
  ],
  L: [
    { team: "England", pts: 9, gd: 4, gf: 4, ga: 0, mp: 3, w: 3, d: 0, l: 0 },
    { team: "Croatia", pts: 6, gd: 1, gf: 2, ga: 1, mp: 3, w: 2, d: 0, l: 1 },
    { team: "Ghana", pts: 3, gd: -1, gf: 2, ga: 3, mp: 3, w: 1, d: 0, l: 2 },
    { team: "Panama", pts: 0, gd: -4, gf: 1, ga: 5, mp: 3, w: 0, d: 0, l: 3 },
  ],
};

/* ── knockout matches ── */

const KNOCKOUT: Record<string, ApiKnockoutMatch[]> = {
  r32: [
    { team1: "South Korea", team2: "Canada", team1_goals: 1, team2_goals: 0, winner: "South Korea", penalties: false, prob_team1: 0.424, prob_draw: 0.323, prob_team2: 0.253 },
    { team1: "Germany", team2: "Morocco", team1_goals: 1, team2_goals: 0, winner: "Germany", penalties: false, prob_team1: 0.621, prob_draw: 0.229, prob_team2: 0.15 },
    { team1: "Netherlands", team2: "Scotland", team1_goals: 1, team2_goals: 0, winner: "Netherlands", penalties: false, prob_team1: 0.733, prob_draw: 0.184, prob_team2: 0.083 },
    { team1: "Brazil", team2: "Japan", team1_goals: 1, team2_goals: 0, winner: "Brazil", penalties: false, prob_team1: 0.611, prob_draw: 0.228, prob_team2: 0.161 },
    { team1: "France", team2: "Sweden", team1_goals: 1, team2_goals: 0, winner: "France", penalties: false, prob_team1: 0.748, prob_draw: 0.192, prob_team2: 0.06 },
    { team1: "Ecuador", team2: "Norway", team1_goals: 1, team2_goals: 0, winner: "Ecuador", penalties: false, prob_team1: 0.373, prob_draw: 0.334, prob_team2: 0.293 },
    { team1: "Mexico", team2: "Senegal", team1_goals: 1, team2_goals: 0, winner: "Mexico", penalties: false, prob_team1: 0.404, prob_draw: 0.329, prob_team2: 0.267 },
    { team1: "England", team2: "DR Congo", team1_goals: 1, team2_goals: 0, winner: "England", penalties: false, prob_team1: 0.765, prob_draw: 0.178, prob_team2: 0.057 },
    { team1: "Turkey", team2: "Bosnia and Herzegovina", team1_goals: 1, team2_goals: 0, winner: "Turkey", penalties: false, prob_team1: 0.74, prob_draw: 0.19, prob_team2: 0.07 },
    { team1: "Belgium", team2: "Czech Republic", team1_goals: 2, team2_goals: 0, winner: "Belgium", penalties: false, prob_team1: 0.626, prob_draw: 0.205, prob_team2: 0.169 },
    { team1: "Portugal", team2: "Croatia", team1_goals: 2, team2_goals: 1, winner: "Portugal", penalties: false, prob_team1: 0.593, prob_draw: 0.207, prob_team2: 0.2 },
    { team1: "Spain", team2: "Algeria", team1_goals: 2, team2_goals: 0, winner: "Spain", penalties: false, prob_team1: 0.817, prob_draw: 0.143, prob_team2: 0.04 },
    { team1: "Switzerland", team2: "Austria", team1_goals: 1, team2_goals: 0, winner: "Switzerland", penalties: false, prob_team1: 0.513, prob_draw: 0.279, prob_team2: 0.208 },
    { team1: "Argentina", team2: "Uruguay", team1_goals: 1, team2_goals: 0, winner: "Argentina", penalties: false, prob_team1: 0.636, prob_draw: 0.276, prob_team2: 0.088 },
    { team1: "Colombia", team2: "Ghana", team1_goals: 1, team2_goals: 0, winner: "Colombia", penalties: false, prob_team1: 0.693, prob_draw: 0.23, prob_team2: 0.077 },
    { team1: "United States", team2: "Egypt", team1_goals: 1, team2_goals: 0, winner: "United States", penalties: false, prob_team1: 0.517, prob_draw: 0.249, prob_team2: 0.234 },
  ],
  r16: [
    { team1: "Germany", team2: "France", team1_goals: 1, team2_goals: 2, winner: "France", penalties: false, prob_team1: 0.364, prob_draw: 0.232, prob_team2: 0.404 },
    { team1: "South Korea", team2: "Netherlands", team1_goals: 0, team2_goals: 1, winner: "Netherlands", penalties: false, prob_team1: 0.149, prob_draw: 0.251, prob_team2: 0.6 },
    { team1: "Brazil", team2: "Ecuador", team1_goals: 1, team2_goals: 0, winner: "Brazil", penalties: false, prob_team1: 0.528, prob_draw: 0.333, prob_team2: 0.14 },
    { team1: "Mexico", team2: "England", team1_goals: 0, team2_goals: 1, winner: "England", penalties: false, prob_team1: 0.219, prob_draw: 0.305, prob_team2: 0.475 },
    { team1: "Portugal", team2: "Spain", team1_goals: 0, team2_goals: 1, winner: "Spain", penalties: false, prob_team1: 0.242, prob_draw: 0.295, prob_team2: 0.464 },
    { team1: "Turkey", team2: "Belgium", team1_goals: 1, team2_goals: 0, winner: "Turkey", penalties: false, prob_team1: 0.421, prob_draw: 0.288, prob_team2: 0.291 },
    { team1: "Argentina", team2: "United States", team1_goals: 1, team2_goals: 0, winner: "Argentina", penalties: false, prob_team1: 0.73, prob_draw: 0.216, prob_team2: 0.054 },
    { team1: "Switzerland", team2: "Colombia", team1_goals: 1, team2_goals: 0, winner: "Switzerland", penalties: false, prob_team1: 0.418, prob_draw: 0.251, prob_team2: 0.331 },
  ],
  qf: [
    { team1: "France", team2: "Netherlands", team1_goals: 1, team2_goals: 0, winner: "France", penalties: false, prob_team1: 0.648, prob_draw: 0.227, prob_team2: 0.125 },
    { team1: "Spain", team2: "Turkey", team1_goals: 1, team2_goals: 0, winner: "Spain", penalties: false, prob_team1: 0.741, prob_draw: 0.191, prob_team2: 0.068 },
    { team1: "Brazil", team2: "England", team1_goals: 1, team2_goals: 0, winner: "Brazil", penalties: false, prob_team1: 0.366, prob_draw: 0.301, prob_team2: 0.333 },
    { team1: "Argentina", team2: "Switzerland", team1_goals: 1, team2_goals: 0, winner: "Argentina", penalties: false, prob_team1: 0.692, prob_draw: 0.216, prob_team2: 0.092 },
  ],
  sf: [
    { team1: "France", team2: "Spain", team1_goals: 1, team2_goals: 0, winner: "France", penalties: false, prob_team1: 0.412, prob_draw: 0.257, prob_team2: 0.331 },
    { team1: "Brazil", team2: "Argentina", team1_goals: 0, team2_goals: 1, winner: "Argentina", penalties: false, prob_team1: 0.336, prob_draw: 0.307, prob_team2: 0.357 },
  ],
  final: [
    { team1: "France", team2: "Argentina", team1_goals: 1, team2_goals: 0, winner: "France", penalties: false, prob_team1: 0.495, prob_draw: 0.264, prob_team2: 0.241 },
  ],
};

/* ── assembled response ── */

const GROUPS = ["A", "B", "C", "D", "E", "F", "G", "H", "I", "J", "K", "L"];

export const DETERMINISTIC_DATA: DeterministicData = {
  champion: "France",
  groups: GROUPS.map((g) => ({
    group: g,
    matches: GROUP_MATCHES[g],
    table: GROUP_TABLES[g],
  })),
  best_thirds: {
    A: "Czech Republic",
    J: "Austria",
    I: "Senegal",
    L: "Ghana",
    B: "Bosnia and Herzegovina",
    C: "Morocco",
    F: "Sweden",
    K: "DR Congo",
  },
  knockout: KNOCKOUT,
};
