/**
 * Pre-computed deterministic prediction results.
 * Generated by scripts/regen_deterministic.py
 *
 * This is the model's single best answer — argmax of predicted probabilities
 * for every match. Unlike Monte Carlo simulation, this always produces the
 * same result.
 */

export const DETERMINISTIC_DATA = {
  "champion": "Spain",
  "groups": [
    {
      "group": "A",
      "matches": [
        {
          "home_team": "Mexico",
          "away_team": "South Africa",
          "home_goals": 1,
          "away_goals": 0,
          "home_pts": 3,
          "away_pts": 0,
          "prob_home": 0.7255,
          "prob_draw": 0.225,
          "prob_away": 0.0495
        },
        {
          "home_team": "South Korea",
          "away_team": "Czech Republic",
          "home_goals": 0,
          "away_goals": 0,
          "home_pts": 1,
          "away_pts": 1,
          "prob_home": 0.2551,
          "prob_draw": 0.5018,
          "prob_away": 0.2431
        },
        {
          "home_team": "Czech Republic",
          "away_team": "South Africa",
          "home_goals": 1,
          "away_goals": 0,
          "home_pts": 3,
          "away_pts": 0,
          "prob_home": 0.529,
          "prob_draw": 0.307,
          "prob_away": 0.164
        },
        {
          "home_team": "Mexico",
          "away_team": "South Korea",
          "home_goals": 0,
          "away_goals": 0,
          "home_pts": 1,
          "away_pts": 1,
          "prob_home": 0.3501,
          "prob_draw": 0.4621,
          "prob_away": 0.1877
        },
        {
          "home_team": "Czech Republic",
          "away_team": "Mexico",
          "home_goals": 0,
          "away_goals": 1,
          "home_pts": 0,
          "away_pts": 3,
          "prob_home": 0.2238,
          "prob_draw": 0.3531,
          "prob_away": 0.4231
        },
        {
          "home_team": "South Africa",
          "away_team": "South Korea",
          "home_goals": 0,
          "away_goals": 1,
          "home_pts": 0,
          "away_pts": 3,
          "prob_home": 0.1281,
          "prob_draw": 0.3304,
          "prob_away": 0.5415
        }
      ],
      "table": [
        {
          "team": "Mexico",
          "pts": 7,
          "gd": 2,
          "gf": 2,
          "ga": 0,
          "mp": 3,
          "w": 2,
          "d": 1,
          "l": 0
        },
        {
          "team": "South Korea",
          "pts": 5,
          "gd": 1,
          "gf": 1,
          "ga": 0,
          "mp": 3,
          "w": 1,
          "d": 2,
          "l": 0
        },
        {
          "team": "Czech Republic",
          "pts": 4,
          "gd": 0,
          "gf": 1,
          "ga": 1,
          "mp": 3,
          "w": 1,
          "d": 1,
          "l": 1
        },
        {
          "team": "South Africa",
          "pts": 0,
          "gd": -3,
          "gf": 0,
          "ga": 3,
          "mp": 3,
          "w": 0,
          "d": 0,
          "l": 3
        }
      ]
    },
    {
      "group": "B",
      "matches": [
        {
          "home_team": "Canada",
          "away_team": "Bosnia and Herzegovina",
          "home_goals": 1,
          "away_goals": 0,
          "home_pts": 3,
          "away_pts": 0,
          "prob_home": 0.5247,
          "prob_draw": 0.2974,
          "prob_away": 0.1779
        },
        {
          "home_team": "Qatar",
          "away_team": "Switzerland",
          "home_goals": 0,
          "away_goals": 1,
          "home_pts": 0,
          "away_pts": 3,
          "prob_home": 0.0577,
          "prob_draw": 0.2217,
          "prob_away": 0.7206
        },
        {
          "home_team": "Switzerland",
          "away_team": "Bosnia and Herzegovina",
          "home_goals": 1,
          "away_goals": 0,
          "home_pts": 3,
          "away_pts": 0,
          "prob_home": 0.6318,
          "prob_draw": 0.2777,
          "prob_away": 0.0905
        },
        {
          "home_team": "Canada",
          "away_team": "Qatar",
          "home_goals": 1,
          "away_goals": 0,
          "home_pts": 3,
          "away_pts": 0,
          "prob_home": 0.6886,
          "prob_draw": 0.2422,
          "prob_away": 0.0692
        },
        {
          "home_team": "Switzerland",
          "away_team": "Canada",
          "home_goals": 0,
          "away_goals": 0,
          "home_pts": 1,
          "away_pts": 1,
          "prob_home": 0.408,
          "prob_draw": 0.4103,
          "prob_away": 0.1817
        },
        {
          "home_team": "Bosnia and Herzegovina",
          "away_team": "Qatar",
          "home_goals": 1,
          "away_goals": 0,
          "home_pts": 3,
          "away_pts": 0,
          "prob_home": 0.4186,
          "prob_draw": 0.3375,
          "prob_away": 0.2439
        }
      ],
      "table": [
        {
          "team": "Canada",
          "pts": 7,
          "gd": 2,
          "gf": 2,
          "ga": 0,
          "mp": 3,
          "w": 2,
          "d": 1,
          "l": 0
        },
        {
          "team": "Switzerland",
          "pts": 7,
          "gd": 2,
          "gf": 2,
          "ga": 0,
          "mp": 3,
          "w": 2,
          "d": 1,
          "l": 0
        },
        {
          "team": "Bosnia and Herzegovina",
          "pts": 3,
          "gd": -1,
          "gf": 1,
          "ga": 2,
          "mp": 3,
          "w": 1,
          "d": 0,
          "l": 2
        },
        {
          "team": "Qatar",
          "pts": 0,
          "gd": -3,
          "gf": 0,
          "ga": 3,
          "mp": 3,
          "w": 0,
          "d": 0,
          "l": 3
        }
      ]
    },
    {
      "group": "C",
      "matches": [
        {
          "home_team": "Brazil",
          "away_team": "Morocco",
          "home_goals": 1,
          "away_goals": 0,
          "home_pts": 3,
          "away_pts": 0,
          "prob_home": 0.498,
          "prob_draw": 0.3584,
          "prob_away": 0.1436
        },
        {
          "home_team": "Haiti",
          "away_team": "Scotland",
          "home_goals": 0,
          "away_goals": 1,
          "home_pts": 0,
          "away_pts": 3,
          "prob_home": 0.1466,
          "prob_draw": 0.3374,
          "prob_away": 0.516
        },
        {
          "home_team": "Scotland",
          "away_team": "Morocco",
          "home_goals": 0,
          "away_goals": 0,
          "home_pts": 1,
          "away_pts": 1,
          "prob_home": 0.2295,
          "prob_draw": 0.4105,
          "prob_away": 0.36
        },
        {
          "home_team": "Brazil",
          "away_team": "Haiti",
          "home_goals": 1,
          "away_goals": 0,
          "home_pts": 3,
          "away_pts": 0,
          "prob_home": 0.7918,
          "prob_draw": 0.164,
          "prob_away": 0.0443
        },
        {
          "home_team": "Scotland",
          "away_team": "Brazil",
          "home_goals": 0,
          "away_goals": 1,
          "home_pts": 0,
          "away_pts": 3,
          "prob_home": 0.1098,
          "prob_draw": 0.3503,
          "prob_away": 0.5399
        },
        {
          "home_team": "Morocco",
          "away_team": "Haiti",
          "home_goals": 1,
          "away_goals": 0,
          "home_pts": 3,
          "away_pts": 0,
          "prob_home": 0.565,
          "prob_draw": 0.352,
          "prob_away": 0.083
        }
      ],
      "table": [
        {
          "team": "Brazil",
          "pts": 9,
          "gd": 3,
          "gf": 3,
          "ga": 0,
          "mp": 3,
          "w": 3,
          "d": 0,
          "l": 0
        },
        {
          "team": "Morocco",
          "pts": 4,
          "gd": 0,
          "gf": 1,
          "ga": 1,
          "mp": 3,
          "w": 1,
          "d": 1,
          "l": 1
        },
        {
          "team": "Scotland",
          "pts": 4,
          "gd": 0,
          "gf": 1,
          "ga": 1,
          "mp": 3,
          "w": 1,
          "d": 1,
          "l": 1
        },
        {
          "team": "Haiti",
          "pts": 0,
          "gd": -3,
          "gf": 0,
          "ga": 3,
          "mp": 3,
          "w": 0,
          "d": 0,
          "l": 3
        }
      ]
    },
    {
      "group": "D",
      "matches": [
        {
          "home_team": "United States",
          "away_team": "Paraguay",
          "home_goals": 0,
          "away_goals": 1,
          "home_pts": 0,
          "away_pts": 3,
          "prob_home": 0.2596,
          "prob_draw": 0.3469,
          "prob_away": 0.3936
        },
        {
          "home_team": "Australia",
          "away_team": "Turkey",
          "home_goals": 0,
          "away_goals": 1,
          "home_pts": 0,
          "away_pts": 3,
          "prob_home": 0.1196,
          "prob_draw": 0.358,
          "prob_away": 0.5224
        },
        {
          "home_team": "United States",
          "away_team": "Australia",
          "home_goals": 0,
          "away_goals": 0,
          "home_pts": 1,
          "away_pts": 1,
          "prob_home": 0.3241,
          "prob_draw": 0.3628,
          "prob_away": 0.3131
        },
        {
          "home_team": "Turkey",
          "away_team": "Paraguay",
          "home_goals": 1,
          "away_goals": 0,
          "home_pts": 3,
          "away_pts": 0,
          "prob_home": 0.4815,
          "prob_draw": 0.3071,
          "prob_away": 0.2114
        },
        {
          "home_team": "Turkey",
          "away_team": "United States",
          "home_goals": 1,
          "away_goals": 0,
          "home_pts": 3,
          "away_pts": 0,
          "prob_home": 0.4611,
          "prob_draw": 0.3499,
          "prob_away": 0.1889
        },
        {
          "home_team": "Paraguay",
          "away_team": "Australia",
          "home_goals": 0,
          "away_goals": 0,
          "home_pts": 1,
          "away_pts": 1,
          "prob_home": 0.3535,
          "prob_draw": 0.3904,
          "prob_away": 0.2561
        }
      ],
      "table": [
        {
          "team": "Turkey",
          "pts": 9,
          "gd": 3,
          "gf": 3,
          "ga": 0,
          "mp": 3,
          "w": 3,
          "d": 0,
          "l": 0
        },
        {
          "team": "Paraguay",
          "pts": 4,
          "gd": 0,
          "gf": 1,
          "ga": 1,
          "mp": 3,
          "w": 1,
          "d": 1,
          "l": 1
        },
        {
          "team": "Australia",
          "pts": 2,
          "gd": -1,
          "gf": 0,
          "ga": 1,
          "mp": 3,
          "w": 0,
          "d": 2,
          "l": 1
        },
        {
          "team": "United States",
          "pts": 1,
          "gd": -2,
          "gf": 0,
          "ga": 2,
          "mp": 3,
          "w": 0,
          "d": 1,
          "l": 2
        }
      ]
    },
    {
      "group": "E",
      "matches": [
        {
          "home_team": "Germany",
          "away_team": "Curaçao",
          "home_goals": 1,
          "away_goals": 0,
          "home_pts": 3,
          "away_pts": 0,
          "prob_home": 0.7606,
          "prob_draw": 0.1743,
          "prob_away": 0.0651
        },
        {
          "home_team": "Ivory Coast",
          "away_team": "Ecuador",
          "home_goals": 0,
          "away_goals": 1,
          "home_pts": 0,
          "away_pts": 3,
          "prob_home": 0.1886,
          "prob_draw": 0.3414,
          "prob_away": 0.47
        },
        {
          "home_team": "Germany",
          "away_team": "Ivory Coast",
          "home_goals": 1,
          "away_goals": 0,
          "home_pts": 3,
          "away_pts": 0,
          "prob_home": 0.6517,
          "prob_draw": 0.2473,
          "prob_away": 0.101
        },
        {
          "home_team": "Ecuador",
          "away_team": "Curaçao",
          "home_goals": 1,
          "away_goals": 0,
          "home_pts": 3,
          "away_pts": 0,
          "prob_home": 0.5005,
          "prob_draw": 0.4282,
          "prob_away": 0.0713
        },
        {
          "home_team": "Ecuador",
          "away_team": "Germany",
          "home_goals": 0,
          "away_goals": 0,
          "home_pts": 1,
          "away_pts": 1,
          "prob_home": 0.1686,
          "prob_draw": 0.4308,
          "prob_away": 0.4006
        },
        {
          "home_team": "Curaçao",
          "away_team": "Ivory Coast",
          "home_goals": 0,
          "away_goals": 1,
          "home_pts": 0,
          "away_pts": 3,
          "prob_home": 0.2143,
          "prob_draw": 0.3514,
          "prob_away": 0.4342
        }
      ],
      "table": [
        {
          "team": "Germany",
          "pts": 7,
          "gd": 2,
          "gf": 2,
          "ga": 0,
          "mp": 3,
          "w": 2,
          "d": 1,
          "l": 0
        },
        {
          "team": "Ecuador",
          "pts": 7,
          "gd": 2,
          "gf": 2,
          "ga": 0,
          "mp": 3,
          "w": 2,
          "d": 1,
          "l": 0
        },
        {
          "team": "Ivory Coast",
          "pts": 3,
          "gd": -1,
          "gf": 1,
          "ga": 2,
          "mp": 3,
          "w": 1,
          "d": 0,
          "l": 2
        },
        {
          "team": "Curaçao",
          "pts": 0,
          "gd": -3,
          "gf": 0,
          "ga": 3,
          "mp": 3,
          "w": 0,
          "d": 0,
          "l": 3
        }
      ]
    },
    {
      "group": "F",
      "matches": [
        {
          "home_team": "Netherlands",
          "away_team": "Japan",
          "home_goals": 1,
          "away_goals": 0,
          "home_pts": 3,
          "away_pts": 0,
          "prob_home": 0.5076,
          "prob_draw": 0.3072,
          "prob_away": 0.1851
        },
        {
          "home_team": "Sweden",
          "away_team": "Tunisia",
          "home_goals": 1,
          "away_goals": 0,
          "home_pts": 3,
          "away_pts": 0,
          "prob_home": 0.4812,
          "prob_draw": 0.3148,
          "prob_away": 0.204
        },
        {
          "home_team": "Netherlands",
          "away_team": "Sweden",
          "home_goals": 1,
          "away_goals": 0,
          "home_pts": 3,
          "away_pts": 0,
          "prob_home": 0.5402,
          "prob_draw": 0.2977,
          "prob_away": 0.1621
        },
        {
          "home_team": "Tunisia",
          "away_team": "Japan",
          "home_goals": 0,
          "away_goals": 1,
          "home_pts": 0,
          "away_pts": 3,
          "prob_home": 0.1177,
          "prob_draw": 0.3703,
          "prob_away": 0.512
        },
        {
          "home_team": "Japan",
          "away_team": "Sweden",
          "home_goals": 1,
          "away_goals": 0,
          "home_pts": 3,
          "away_pts": 0,
          "prob_home": 0.3684,
          "prob_draw": 0.3439,
          "prob_away": 0.2878
        },
        {
          "home_team": "Tunisia",
          "away_team": "Netherlands",
          "home_goals": 0,
          "away_goals": 1,
          "home_pts": 0,
          "away_pts": 3,
          "prob_home": 0.0619,
          "prob_draw": 0.2722,
          "prob_away": 0.6659
        }
      ],
      "table": [
        {
          "team": "Netherlands",
          "pts": 9,
          "gd": 3,
          "gf": 3,
          "ga": 0,
          "mp": 3,
          "w": 3,
          "d": 0,
          "l": 0
        },
        {
          "team": "Japan",
          "pts": 6,
          "gd": 1,
          "gf": 2,
          "ga": 1,
          "mp": 3,
          "w": 2,
          "d": 0,
          "l": 1
        },
        {
          "team": "Sweden",
          "pts": 3,
          "gd": -1,
          "gf": 1,
          "ga": 2,
          "mp": 3,
          "w": 1,
          "d": 0,
          "l": 2
        },
        {
          "team": "Tunisia",
          "pts": 0,
          "gd": -3,
          "gf": 0,
          "ga": 3,
          "mp": 3,
          "w": 0,
          "d": 0,
          "l": 3
        }
      ]
    },
    {
      "group": "G",
      "matches": [
        {
          "home_team": "Iran",
          "away_team": "New Zealand",
          "home_goals": 0,
          "away_goals": 0,
          "home_pts": 1,
          "away_pts": 1,
          "prob_home": 0.3529,
          "prob_draw": 0.4632,
          "prob_away": 0.1839
        },
        {
          "home_team": "Belgium",
          "away_team": "Egypt",
          "home_goals": 1,
          "away_goals": 0,
          "home_pts": 3,
          "away_pts": 0,
          "prob_home": 0.4356,
          "prob_draw": 0.3322,
          "prob_away": 0.2322
        },
        {
          "home_team": "Belgium",
          "away_team": "Iran",
          "home_goals": 1,
          "away_goals": 0,
          "home_pts": 3,
          "away_pts": 0,
          "prob_home": 0.4508,
          "prob_draw": 0.3208,
          "prob_away": 0.2284
        },
        {
          "home_team": "New Zealand",
          "away_team": "Egypt",
          "home_goals": 0,
          "away_goals": 1,
          "home_pts": 0,
          "away_pts": 3,
          "prob_home": 0.2023,
          "prob_draw": 0.3338,
          "prob_away": 0.464
        },
        {
          "home_team": "Egypt",
          "away_team": "Iran",
          "home_goals": 0,
          "away_goals": 0,
          "home_pts": 1,
          "away_pts": 1,
          "prob_home": 0.2437,
          "prob_draw": 0.3931,
          "prob_away": 0.3632
        },
        {
          "home_team": "New Zealand",
          "away_team": "Belgium",
          "home_goals": 0,
          "away_goals": 1,
          "home_pts": 0,
          "away_pts": 3,
          "prob_home": 0.1184,
          "prob_draw": 0.2724,
          "prob_away": 0.6091
        }
      ],
      "table": [
        {
          "team": "Belgium",
          "pts": 9,
          "gd": 3,
          "gf": 3,
          "ga": 0,
          "mp": 3,
          "w": 3,
          "d": 0,
          "l": 0
        },
        {
          "team": "Egypt",
          "pts": 4,
          "gd": 0,
          "gf": 1,
          "ga": 1,
          "mp": 3,
          "w": 1,
          "d": 1,
          "l": 1
        },
        {
          "team": "Iran",
          "pts": 2,
          "gd": -1,
          "gf": 0,
          "ga": 1,
          "mp": 3,
          "w": 0,
          "d": 2,
          "l": 1
        },
        {
          "team": "New Zealand",
          "pts": 1,
          "gd": -2,
          "gf": 0,
          "ga": 2,
          "mp": 3,
          "w": 0,
          "d": 1,
          "l": 2
        }
      ]
    },
    {
      "group": "H",
      "matches": [
        {
          "home_team": "Spain",
          "away_team": "Cape Verde",
          "home_goals": 1,
          "away_goals": 0,
          "home_pts": 3,
          "away_pts": 0,
          "prob_home": 0.7004,
          "prob_draw": 0.227,
          "prob_away": 0.0726
        },
        {
          "home_team": "Saudi Arabia",
          "away_team": "Uruguay",
          "home_goals": 0,
          "away_goals": 1,
          "home_pts": 0,
          "away_pts": 3,
          "prob_home": 0.152,
          "prob_draw": 0.3712,
          "prob_away": 0.4768
        },
        {
          "home_team": "Spain",
          "away_team": "Saudi Arabia",
          "home_goals": 2,
          "away_goals": 0,
          "home_pts": 3,
          "away_pts": 0,
          "prob_home": 0.7718,
          "prob_draw": 0.1714,
          "prob_away": 0.0568
        },
        {
          "home_team": "Uruguay",
          "away_team": "Cape Verde",
          "home_goals": 1,
          "away_goals": 0,
          "home_pts": 3,
          "away_pts": 0,
          "prob_home": 0.6263,
          "prob_draw": 0.2882,
          "prob_away": 0.0855
        },
        {
          "home_team": "Cape Verde",
          "away_team": "Saudi Arabia",
          "home_goals": 0,
          "away_goals": 0,
          "home_pts": 1,
          "away_pts": 1,
          "prob_home": 0.3195,
          "prob_draw": 0.3585,
          "prob_away": 0.322
        },
        {
          "home_team": "Uruguay",
          "away_team": "Spain",
          "home_goals": 0,
          "away_goals": 1,
          "home_pts": 0,
          "away_pts": 3,
          "prob_home": 0.1078,
          "prob_draw": 0.4159,
          "prob_away": 0.4763
        }
      ],
      "table": [
        {
          "team": "Spain",
          "pts": 9,
          "gd": 4,
          "gf": 4,
          "ga": 0,
          "mp": 3,
          "w": 3,
          "d": 0,
          "l": 0
        },
        {
          "team": "Uruguay",
          "pts": 6,
          "gd": 1,
          "gf": 2,
          "ga": 1,
          "mp": 3,
          "w": 2,
          "d": 0,
          "l": 1
        },
        {
          "team": "Cape Verde",
          "pts": 1,
          "gd": -2,
          "gf": 0,
          "ga": 2,
          "mp": 3,
          "w": 0,
          "d": 1,
          "l": 2
        },
        {
          "team": "Saudi Arabia",
          "pts": 1,
          "gd": -3,
          "gf": 0,
          "ga": 3,
          "mp": 3,
          "w": 0,
          "d": 1,
          "l": 2
        }
      ]
    },
    {
      "group": "I",
      "matches": [
        {
          "home_team": "France",
          "away_team": "Senegal",
          "home_goals": 1,
          "away_goals": 0,
          "home_pts": 3,
          "away_pts": 0,
          "prob_home": 0.5184,
          "prob_draw": 0.3229,
          "prob_away": 0.1587
        },
        {
          "home_team": "Iraq",
          "away_team": "Norway",
          "home_goals": 0,
          "away_goals": 1,
          "home_pts": 0,
          "away_pts": 3,
          "prob_home": 0.0867,
          "prob_draw": 0.3087,
          "prob_away": 0.6047
        },
        {
          "home_team": "France",
          "away_team": "Iraq",
          "home_goals": 1,
          "away_goals": 0,
          "home_pts": 3,
          "away_pts": 0,
          "prob_home": 0.6713,
          "prob_draw": 0.2407,
          "prob_away": 0.088
        },
        {
          "home_team": "Norway",
          "away_team": "Senegal",
          "home_goals": 1,
          "away_goals": 0,
          "home_pts": 3,
          "away_pts": 0,
          "prob_home": 0.4221,
          "prob_draw": 0.3141,
          "prob_away": 0.2638
        },
        {
          "home_team": "Norway",
          "away_team": "France",
          "home_goals": 0,
          "away_goals": 1,
          "home_pts": 0,
          "away_pts": 3,
          "prob_home": 0.1811,
          "prob_draw": 0.3091,
          "prob_away": 0.5098
        },
        {
          "home_team": "Senegal",
          "away_team": "Iraq",
          "home_goals": 1,
          "away_goals": 0,
          "home_pts": 3,
          "away_pts": 0,
          "prob_home": 0.5906,
          "prob_draw": 0.3027,
          "prob_away": 0.1067
        }
      ],
      "table": [
        {
          "team": "France",
          "pts": 9,
          "gd": 3,
          "gf": 3,
          "ga": 0,
          "mp": 3,
          "w": 3,
          "d": 0,
          "l": 0
        },
        {
          "team": "Norway",
          "pts": 6,
          "gd": 1,
          "gf": 2,
          "ga": 1,
          "mp": 3,
          "w": 2,
          "d": 0,
          "l": 1
        },
        {
          "team": "Senegal",
          "pts": 3,
          "gd": -1,
          "gf": 1,
          "ga": 2,
          "mp": 3,
          "w": 1,
          "d": 0,
          "l": 2
        },
        {
          "team": "Iraq",
          "pts": 0,
          "gd": -3,
          "gf": 0,
          "ga": 3,
          "mp": 3,
          "w": 0,
          "d": 0,
          "l": 3
        }
      ]
    },
    {
      "group": "J",
      "matches": [
        {
          "home_team": "Argentina",
          "away_team": "Algeria",
          "home_goals": 1,
          "away_goals": 0,
          "home_pts": 3,
          "away_pts": 0,
          "prob_home": 0.6409,
          "prob_draw": 0.2708,
          "prob_away": 0.0882
        },
        {
          "home_team": "Austria",
          "away_team": "Jordan",
          "home_goals": 1,
          "away_goals": 0,
          "home_pts": 3,
          "away_pts": 0,
          "prob_home": 0.5274,
          "prob_draw": 0.2767,
          "prob_away": 0.1959
        },
        {
          "home_team": "Argentina",
          "away_team": "Austria",
          "home_goals": 1,
          "away_goals": 0,
          "home_pts": 3,
          "away_pts": 0,
          "prob_home": 0.5407,
          "prob_draw": 0.3379,
          "prob_away": 0.1213
        },
        {
          "home_team": "Jordan",
          "away_team": "Algeria",
          "home_goals": 0,
          "away_goals": 1,
          "home_pts": 0,
          "away_pts": 3,
          "prob_home": 0.2169,
          "prob_draw": 0.3602,
          "prob_away": 0.4229
        },
        {
          "home_team": "Algeria",
          "away_team": "Austria",
          "home_goals": 0,
          "away_goals": 0,
          "home_pts": 1,
          "away_pts": 1,
          "prob_home": 0.2532,
          "prob_draw": 0.3761,
          "prob_away": 0.3706
        },
        {
          "home_team": "Jordan",
          "away_team": "Argentina",
          "home_goals": 0,
          "away_goals": 1,
          "home_pts": 0,
          "away_pts": 3,
          "prob_home": 0.0699,
          "prob_draw": 0.2639,
          "prob_away": 0.6662
        }
      ],
      "table": [
        {
          "team": "Argentina",
          "pts": 9,
          "gd": 3,
          "gf": 3,
          "ga": 0,
          "mp": 3,
          "w": 3,
          "d": 0,
          "l": 0
        },
        {
          "team": "Algeria",
          "pts": 4,
          "gd": 0,
          "gf": 1,
          "ga": 1,
          "mp": 3,
          "w": 1,
          "d": 1,
          "l": 1
        },
        {
          "team": "Austria",
          "pts": 4,
          "gd": 0,
          "gf": 1,
          "ga": 1,
          "mp": 3,
          "w": 1,
          "d": 1,
          "l": 1
        },
        {
          "team": "Jordan",
          "pts": 0,
          "gd": -3,
          "gf": 0,
          "ga": 3,
          "mp": 3,
          "w": 0,
          "d": 0,
          "l": 3
        }
      ]
    },
    {
      "group": "K",
      "matches": [
        {
          "home_team": "Portugal",
          "away_team": "DR Congo",
          "home_goals": 1,
          "away_goals": 0,
          "home_pts": 3,
          "away_pts": 0,
          "prob_home": 0.5901,
          "prob_draw": 0.2911,
          "prob_away": 0.1188
        },
        {
          "home_team": "Uzbekistan",
          "away_team": "Colombia",
          "home_goals": 0,
          "away_goals": 1,
          "home_pts": 0,
          "away_pts": 3,
          "prob_home": 0.1557,
          "prob_draw": 0.3664,
          "prob_away": 0.478
        },
        {
          "home_team": "Portugal",
          "away_team": "Uzbekistan",
          "home_goals": 1,
          "away_goals": 0,
          "home_pts": 3,
          "away_pts": 0,
          "prob_home": 0.5992,
          "prob_draw": 0.2646,
          "prob_away": 0.1361
        },
        {
          "home_team": "Colombia",
          "away_team": "DR Congo",
          "home_goals": 1,
          "away_goals": 0,
          "home_pts": 3,
          "away_pts": 0,
          "prob_home": 0.5749,
          "prob_draw": 0.3078,
          "prob_away": 0.1174
        },
        {
          "home_team": "Colombia",
          "away_team": "Portugal",
          "home_goals": 0,
          "away_goals": 1,
          "home_pts": 0,
          "away_pts": 3,
          "prob_home": 0.2891,
          "prob_draw": 0.3297,
          "prob_away": 0.3812
        },
        {
          "home_team": "DR Congo",
          "away_team": "Uzbekistan",
          "home_goals": 0,
          "away_goals": 0,
          "home_pts": 1,
          "away_pts": 1,
          "prob_home": 0.2417,
          "prob_draw": 0.417,
          "prob_away": 0.3413
        }
      ],
      "table": [
        {
          "team": "Portugal",
          "pts": 9,
          "gd": 3,
          "gf": 3,
          "ga": 0,
          "mp": 3,
          "w": 3,
          "d": 0,
          "l": 0
        },
        {
          "team": "Colombia",
          "pts": 6,
          "gd": 1,
          "gf": 2,
          "ga": 1,
          "mp": 3,
          "w": 2,
          "d": 0,
          "l": 1
        },
        {
          "team": "DR Congo",
          "pts": 1,
          "gd": -2,
          "gf": 0,
          "ga": 2,
          "mp": 3,
          "w": 0,
          "d": 1,
          "l": 2
        },
        {
          "team": "Uzbekistan",
          "pts": 1,
          "gd": -2,
          "gf": 0,
          "ga": 2,
          "mp": 3,
          "w": 0,
          "d": 1,
          "l": 2
        }
      ]
    },
    {
      "group": "L",
      "matches": [
        {
          "home_team": "England",
          "away_team": "Croatia",
          "home_goals": 1,
          "away_goals": 0,
          "home_pts": 3,
          "away_pts": 0,
          "prob_home": 0.5193,
          "prob_draw": 0.3077,
          "prob_away": 0.173
        },
        {
          "home_team": "Ghana",
          "away_team": "Panama",
          "home_goals": 0,
          "away_goals": 1,
          "home_pts": 0,
          "away_pts": 3,
          "prob_home": 0.2414,
          "prob_draw": 0.3386,
          "prob_away": 0.42
        },
        {
          "home_team": "England",
          "away_team": "Ghana",
          "home_goals": 1,
          "away_goals": 0,
          "home_pts": 3,
          "away_pts": 0,
          "prob_home": 0.5683,
          "prob_draw": 0.3231,
          "prob_away": 0.1086
        },
        {
          "home_team": "Panama",
          "away_team": "Croatia",
          "home_goals": 0,
          "away_goals": 1,
          "home_pts": 0,
          "away_pts": 3,
          "prob_home": 0.1237,
          "prob_draw": 0.3452,
          "prob_away": 0.5311
        },
        {
          "home_team": "Panama",
          "away_team": "England",
          "home_goals": 0,
          "away_goals": 1,
          "home_pts": 0,
          "away_pts": 3,
          "prob_home": 0.0667,
          "prob_draw": 0.3251,
          "prob_away": 0.6081
        },
        {
          "home_team": "Croatia",
          "away_team": "Ghana",
          "home_goals": 1,
          "away_goals": 0,
          "home_pts": 3,
          "away_pts": 0,
          "prob_home": 0.5588,
          "prob_draw": 0.3198,
          "prob_away": 0.1214
        }
      ],
      "table": [
        {
          "team": "England",
          "pts": 9,
          "gd": 3,
          "gf": 3,
          "ga": 0,
          "mp": 3,
          "w": 3,
          "d": 0,
          "l": 0
        },
        {
          "team": "Croatia",
          "pts": 6,
          "gd": 1,
          "gf": 2,
          "ga": 1,
          "mp": 3,
          "w": 2,
          "d": 0,
          "l": 1
        },
        {
          "team": "Panama",
          "pts": 3,
          "gd": -1,
          "gf": 1,
          "ga": 2,
          "mp": 3,
          "w": 1,
          "d": 0,
          "l": 2
        },
        {
          "team": "Ghana",
          "pts": 0,
          "gd": -3,
          "gf": 0,
          "ga": 3,
          "mp": 3,
          "w": 0,
          "d": 0,
          "l": 3
        }
      ]
    }
  ],
  "best_thirds": {
    "A": "Czech Republic",
    "C": "Scotland",
    "J": "Austria",
    "B": "Bosnia and Herzegovina",
    "E": "Ivory Coast",
    "F": "Sweden",
    "I": "Senegal",
    "L": "Panama"
  },
  "knockout": {
    "r32": [
      {
        "team1": "South Korea",
        "team2": "Switzerland",
        "team1_goals": 0,
        "team2_goals": 1,
        "winner": "Switzerland",
        "penalties": false,
        "prob_team1": 0.1043,
        "prob_draw": 0.4465,
        "prob_team2": 0.4492
      },
      {
        "team1": "Germany",
        "team2": "Scotland",
        "team1_goals": 1,
        "team2_goals": 0,
        "winner": "Germany",
        "penalties": false,
        "prob_team1": 0.5544,
        "prob_draw": 0.2952,
        "prob_team2": 0.1503
      },
      {
        "team1": "Netherlands",
        "team2": "Morocco",
        "team1_goals": 1,
        "team2_goals": 0,
        "winner": "Netherlands",
        "penalties": false,
        "prob_team1": 0.4585,
        "prob_draw": 0.3681,
        "prob_team2": 0.1734
      },
      {
        "team1": "Brazil",
        "team2": "Japan",
        "team1_goals": 1,
        "team2_goals": 0,
        "winner": "Brazil",
        "penalties": false,
        "prob_team1": 0.4295,
        "prob_draw": 0.3582,
        "prob_team2": 0.2123
      },
      {
        "team1": "France",
        "team2": "Sweden",
        "team1_goals": 1,
        "team2_goals": 0,
        "winner": "France",
        "penalties": false,
        "prob_team1": 0.6232,
        "prob_draw": 0.2864,
        "prob_team2": 0.0904
      },
      {
        "team1": "Ecuador",
        "team2": "Norway",
        "team1_goals": 0,
        "team2_goals": 0,
        "winner": "Norway",
        "penalties": true,
        "prob_team1": 0.2427,
        "prob_draw": 0.3896,
        "prob_team2": 0.3678
      },
      {
        "team1": "Mexico",
        "team2": "Ivory Coast",
        "team1_goals": 0,
        "team2_goals": 0,
        "winner": "Mexico",
        "penalties": true,
        "prob_team1": 0.4175,
        "prob_draw": 0.4419,
        "prob_team2": 0.1407
      },
      {
        "team1": "England",
        "team2": "Senegal",
        "team1_goals": 1,
        "team2_goals": 0,
        "winner": "England",
        "penalties": false,
        "prob_team1": 0.6621,
        "prob_draw": 0.2615,
        "prob_team2": 0.0765
      },
      {
        "team1": "Turkey",
        "team2": "Bosnia and Herzegovina",
        "team1_goals": 1,
        "team2_goals": 0,
        "winner": "Turkey",
        "penalties": false,
        "prob_team1": 0.5991,
        "prob_draw": 0.2954,
        "prob_team2": 0.1055
      },
      {
        "team1": "Belgium",
        "team2": "Czech Republic",
        "team1_goals": 1,
        "team2_goals": 0,
        "winner": "Belgium",
        "penalties": false,
        "prob_team1": 0.4779,
        "prob_draw": 0.3089,
        "prob_team2": 0.2131
      },
      {
        "team1": "Colombia",
        "team2": "Croatia",
        "team1_goals": 0,
        "team2_goals": 0,
        "winner": "Colombia",
        "penalties": true,
        "prob_team1": 0.3516,
        "prob_draw": 0.3592,
        "prob_team2": 0.2892
      },
      {
        "team1": "Spain",
        "team2": "Algeria",
        "team1_goals": 1,
        "team2_goals": 0,
        "winner": "Spain",
        "penalties": false,
        "prob_team1": 0.7547,
        "prob_draw": 0.1831,
        "prob_team2": 0.0622
      },
      {
        "team1": "Canada",
        "team2": "Austria",
        "team1_goals": 0,
        "team2_goals": 0,
        "winner": "Austria",
        "penalties": true,
        "prob_team1": 0.2538,
        "prob_draw": 0.3915,
        "prob_team2": 0.3547
      },
      {
        "team1": "Argentina",
        "team2": "Uruguay",
        "team1_goals": 1,
        "team2_goals": 0,
        "winner": "Argentina",
        "penalties": false,
        "prob_team1": 0.4577,
        "prob_draw": 0.4327,
        "prob_team2": 0.1096
      },
      {
        "team1": "Portugal",
        "team2": "Panama",
        "team1_goals": 1,
        "team2_goals": 0,
        "winner": "Portugal",
        "penalties": false,
        "prob_team1": 0.606,
        "prob_draw": 0.2739,
        "prob_team2": 0.1202
      },
      {
        "team1": "Paraguay",
        "team2": "Egypt",
        "team1_goals": 0,
        "team2_goals": 0,
        "winner": "Paraguay",
        "penalties": true,
        "prob_team1": 0.3789,
        "prob_draw": 0.4375,
        "prob_team2": 0.1836
      }
    ],
    "r16": [
      {
        "team1": "Germany",
        "team2": "France",
        "team1_goals": 0,
        "team2_goals": 1,
        "winner": "France",
        "penalties": false,
        "prob_team1": 0.2355,
        "prob_draw": 0.3163,
        "prob_team2": 0.4482
      },
      {
        "team1": "Switzerland",
        "team2": "Netherlands",
        "team1_goals": 0,
        "team2_goals": 1,
        "winner": "Netherlands",
        "penalties": false,
        "prob_team1": 0.1621,
        "prob_draw": 0.3734,
        "prob_team2": 0.4646
      },
      {
        "team1": "Brazil",
        "team2": "Norway",
        "team1_goals": 0,
        "team2_goals": 0,
        "winner": "Brazil",
        "penalties": true,
        "prob_team1": 0.2856,
        "prob_draw": 0.4393,
        "prob_team2": 0.2751
      },
      {
        "team1": "Mexico",
        "team2": "England",
        "team1_goals": 0,
        "team2_goals": 1,
        "winner": "England",
        "penalties": false,
        "prob_team1": 0.1232,
        "prob_draw": 0.3593,
        "prob_team2": 0.5175
      },
      {
        "team1": "Colombia",
        "team2": "Spain",
        "team1_goals": 0,
        "team2_goals": 1,
        "winner": "Spain",
        "penalties": false,
        "prob_team1": 0.1195,
        "prob_draw": 0.4085,
        "prob_team2": 0.472
      },
      {
        "team1": "Turkey",
        "team2": "Belgium",
        "team1_goals": 0,
        "team2_goals": 0,
        "winner": "Belgium",
        "penalties": true,
        "prob_team1": 0.2987,
        "prob_draw": 0.3743,
        "prob_team2": 0.327
      },
      {
        "team1": "Argentina",
        "team2": "Paraguay",
        "team1_goals": 1,
        "team2_goals": 0,
        "winner": "Argentina",
        "penalties": false,
        "prob_team1": 0.4634,
        "prob_draw": 0.4451,
        "prob_team2": 0.0916
      },
      {
        "team1": "Austria",
        "team2": "Portugal",
        "team1_goals": 0,
        "team2_goals": 1,
        "winner": "Portugal",
        "penalties": false,
        "prob_team1": 0.1602,
        "prob_draw": 0.3249,
        "prob_team2": 0.5148
      }
    ],
    "qf": [
      {
        "team1": "France",
        "team2": "Netherlands",
        "team1_goals": 1,
        "team2_goals": 0,
        "winner": "France",
        "penalties": false,
        "prob_team1": 0.4965,
        "prob_draw": 0.3076,
        "prob_team2": 0.1959
      },
      {
        "team1": "Spain",
        "team2": "Belgium",
        "team1_goals": 1,
        "team2_goals": 0,
        "winner": "Spain",
        "penalties": false,
        "prob_team1": 0.5462,
        "prob_draw": 0.3186,
        "prob_team2": 0.1352
      },
      {
        "team1": "Brazil",
        "team2": "England",
        "team1_goals": 0,
        "team2_goals": 0,
        "winner": "England",
        "penalties": true,
        "prob_team1": 0.2301,
        "prob_draw": 0.4288,
        "prob_team2": 0.3412
      },
      {
        "team1": "Argentina",
        "team2": "Portugal",
        "team1_goals": 1,
        "team2_goals": 0,
        "winner": "Argentina",
        "penalties": false,
        "prob_team1": 0.458,
        "prob_draw": 0.3563,
        "prob_team2": 0.1857
      }
    ],
    "sf": [
      {
        "team1": "France",
        "team2": "Spain",
        "team1_goals": 0,
        "team2_goals": 1,
        "winner": "Spain",
        "penalties": false,
        "prob_team1": 0.2639,
        "prob_draw": 0.3398,
        "prob_team2": 0.3962
      },
      {
        "team1": "England",
        "team2": "Argentina",
        "team1_goals": 0,
        "team2_goals": 0,
        "winner": "Argentina",
        "penalties": true,
        "prob_team1": 0.3049,
        "prob_draw": 0.3588,
        "prob_team2": 0.3363
      }
    ],
    "final": [
      {
        "team1": "Spain",
        "team2": "Argentina",
        "team1_goals": 1,
        "team2_goals": 0,
        "winner": "Spain",
        "penalties": false,
        "prob_team1": 0.373,
        "prob_draw": 0.3622,
        "prob_team2": 0.2648
      }
    ]
  }
};
